/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fbm.register;

import java.util.ArrayList;

import nc.vo.fbm.pub.BaseinfoVO;
import nc.vo.ml.NCLangRes4VoTransl;
import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b> 收票、开票登记表VO
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2007-9-12
 * 
 * @author author
 * @version Your Project 1.0
 */
public class RegisterVO extends SuperVO {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	public static final String TABLENAME = "fbm_register";
	public static final String BASEINFO_TAB = "table_baseinfo";

	private BaseinfoVO baseinfoVo = null;

	private String def5;// 自定义项5
	private String pk_corp;// 收票或者付票公司pk
	private UFDouble poundagemoney;// 手续费金额
	private String cctype;// 授信类型
	private String keepunit;// 存放地点，参照客商基本档案PK，一般是pk_corp对应的客商基本档案
	private String voperatorid;// 录入人PK
	private String gathertype;// 收票类型 枚举值请参考FbmBusConstant的 收票来源类型
	private String vapprovenote;// 审核批语
	private UFDouble brate;// 本币汇率
	private Integer vbillstatus;// 单据状态
	private String holdunit;// 持票单位，参照客商基本档案PK
	private String pk_source;// 上游登记表PK
	private String pk_org;// 组织PK，暂时不用
	private UFDouble frate;// 辅币汇率
	private UFDouble securityrate;// 保证金比例
	private UFDouble moneyf;// 辅币金额
	private String paybillunit; // 付票单位，参照客商基本档案PK
	private UFDouble securitymoney;// 保证金金额
	private String vbillno;// 单据编号
	private UFBoolean isnewbill;// 是否新收票
	private String impawnmode;// 质押类型
	private String pk_register;// 登记表主键
	private String pk_baseinfo;// 票据基本信息PK
	private String def1;// 自定义项1
	private String note;// 备注
	private UFDate dapprovedate;// 审核日期
	private String pk_billtypecode;// 单据类型 36GA表示应收票据，36GL表示应付票据
	private UFDate gatherdate;// 收票日期
	private String vapproveid;// 审核人PK
	private String def2;// 自定义项2
	private UFDouble moneyy;// 票面金额原币
	private String securityaccount;// 保证金账号PK
	private String def4;// 自定义项4
	private UFDouble moneyb;// 票面金额本币
	private String def3;// 自定义项3
	private UFDate doperatedate;// 录入日期
	private String verifyman;// 核销人
	private UFBoolean isverify;
	private UFDate verifydate;// 核销日期
	private String registerno;
	private UFDateTime ts;
	private Integer dr;
	private String pk_loanbank;
	private UFBoolean sfflag;// 已收票、已付票标记
	private UFBoolean isacccust;// 银行账号是否手工录入
	private UFBoolean isrecacccust;
	private UFDouble securitymoneyf;// 保证金金额辅币
	private UFDouble securitymoneyb;// 保证金金额本币
	private UFDouble poundagemoneyf;// 手续费辅币
	private UFDouble poundagemoneyb;// 手续费本币
	private String dept;// 部门PK
	private UFBoolean voucher;// 已制证标志
	private String vvouchermanid;// 制证人
	private UFDate dvoucherdate;// 制证日期
	private String invoiceitem;// 开票收入项目 2008-11-22 改为保证金支出项目
	private String chargeitem;// 手续费支出项目
	private String invoiceplanitem;// 付票是：开票收入计划项目 ；收票时：收票收入计划项目
	private String chargeplanitem;// 手续费支出计划项目
	private String gatherplanitem; // 收票收入计划项目
	private String invoiceoutplanitem; // 开票支出计划项目。
	private String gatheritem; // 收票收支项目
	private String invoiceoutitem; // 付票收支项目

	// fbm_baseinfo内容
	public String paybankacc;// 付款单位银行账号

	public String paybank;// 暂时不用

	public UFDate enddate;// 票据到期日

	public String receivebank;// 暂时不用

	public String acceptanceno;// 承兑协议编号

	public UFBoolean disable;// 是否废票

	public String fbmbilltype;// 票据类型

	public String payunit;// 付款单位，参照客商基本档案PK

	public String receiveunit;// 收款单位，参照客商基本档案PK

	public UFDate invoicedate;// 开票日期

	public String invoiceunit;// 开票单位，参照客商基本档案PK

	public String contractno;// 合同编号

	public String receivebankacc;// 收款单位银行账号

	public String pk_curr;// 币种PK

	public String fbmbillno;// 票据编号

	public String receiveunitname;// 收款单位名称

	public String receiveaccname; // 收款行全称

	public String orientation;// 票据方向 参考FbmBusConstant

	public String invoiceunitname;// 开票单位名称

	public String payunitname;// 付款单位名称（手工录入使用）

	public String paybankaccode;// 付款单位银行账号code

	public String receivebankaccode;// 收款单位银行账号code
	
	public String firstman;//首次录入人
	
	public UFDateTime approvetime;//审核时间戳

	// 付款收款账号携带的字段
	private String payaccname;// 付款行全称

	private String paybankname;// 付款银行名称
	private String receivebankname;// 收款银行名称

	/**
	 * 贴现试算界面使用，贴现利率相关信息,数据库中没有对应项 贴现净值 = 票面金额 - 贴现利息
	 */
	private String txnllfa;// 贴现年利率方案 - in/no
	private UFDouble txnlv;// 贴现年利率 - in/no
	private UFDouble txyll;// 贴现月利率 - in/no
	private UFDouble txrll;// 贴现日利率 in/no
	private UFDate qxrq;// 起效日期 - in/no
	private UFDate txrq;// 贴现日期 - in
	private UFDouble txlx;// 贴现利息 - out
	private UFDouble txjz;// 贴现净值 - out
	private Integer llts;// 利率天数 - in
	private Integer txts;// 贴现天数 - in
	private Integer discountdelaydaynum;// 贴现延迟天数 - in
	private UFBoolean choice = UFBoolean.FALSE;

	/**
	 * 临时变量，保存是否要回写计划,true：回写；null || false：不回写
	 */
	private UFBoolean writeplan;

	

	private UFBoolean writebankacc;

	private UFBoolean writeinneracc;

	private String registerstatus;//收付票最新状态
	/**
	 * 说明:自定义项5
	 */
	public static final String DEF5 = "def5";
	/**
	 * 说明:公司
	 */
	public static final String PK_CORP = "pk_corp";
	/**
	 * 说明:手续费金额
	 */
	public static final String POUNDAGEMONEY = "poundagemoney";
	/**
	 * 说明:授信类型
	 */
	public static final String CCTYPE = "cctype";
	/**
	 * 说明:存放地点
	 */
	public static final String KEEPUNIT = "keepunit";
	/**
	 * 说明:操作人
	 */
	public static final String VOPERATORID = "voperatorid";
	/**
	 * 说明:收票来源类型
	 */
	public static final String GATHERTYPE = "gathertype";
	/**
	 * 说明:审核批语
	 */
	public static final String VAPPROVENOTE = "vapprovenote";
	/**
	 * 说明:本币汇率
	 */
	public static final String BRATE = "brate";
	/**
	 * 说明:单据状态
	 */
	public static final String VBILLSTATUS = "vbillstatus";
	/**
	 * 说明:持票单位
	 */
	public static final String HOLDUNIT = "holdunit";
	/**
	 * 说明:来源单据
	 */
	public static final String PK_SOURCE = "pk_source";
	/**
	 * 说明:组织
	 */
	public static final String PK_ORG = "pk_org";
	/**
	 * 说明:辅币汇率
	 */
	public static final String FRATE = "frate";
	/**
	 * 说明:保证金比例
	 */
	public static final String SECURITYRATE = "securityrate";
	/**
	 * 说明:辅币金额
	 */
	public static final String MONEYF = "moneyf";
	/**
	 * 说明:付票单位
	 */
	public static final String PAYBILLUNIT = "paybillunit";
	/**
	 * 说明:保证金金额
	 */
	public static final String SECURITYMONEY = "securitymoney";
	/**
	 * 说明:单据编号
	 */
	public static final String VBILLNO = "vbillno";
	/**
	 * 说明:是否新票据
	 */
	public static final String ISNEWBILL = "isnewbill";
	/**
	 * 说明:担保方式
	 */
	public static final String IMPAWNMODE = "impawnmode";
	/**
	 * 说明:主键
	 */
	public static final String PK_BILL = "pk_register";
	/**
	 * 说明:票据基本信息
	 */
	public static final String PK_BASEINFO = "pk_baseinfo";
	/**
	 * 说明:自定义项1
	 */
	public static final String DEF1 = "def1";
	/**
	 * 说明:备注
	 */
	public static final String NOTE = "note";
	/**
	 * 说明:审核日期
	 */
	public static final String DAPPROVEDATE = "dapprovedate";
	/**
	 * 说明:单据类型
	 */
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	/**
	 * 说明:收票日期
	 */
	public static final String GATHERDATE = "gatherdate";
	/**
	 * 说明:序列号
	 */
	public static final String SERIALNO = "serialno";
	/**
	 * 说明:审核人
	 */
	public static final String VAPPROVEID = "vapproveid";
	/**
	 * 说明:自定义项2
	 */
	public static final String DEF2 = "def2";
	/**
	 * 说明:票据金额
	 */
	public static final String MONEYY = "moneyy";
	/**
	 * 说明:保证金账号
	 */
	public static final String SECURITYACCOUNT = "securityaccount";
	/**
	 * 说明:自定义项4
	 */
	public static final String DEF4 = "def4";
	/**
	 * 说明:本币金额
	 */
	public static final String MONEYB = "moneyb";
	/**
	 * 说明:自定义项3
	 */
	public static final String DEF3 = "def3";
	/**
	 * 说明:操作日期
	 */
	public static final String DOPERATEDATE = "doperatedate";
	/**
	 * PK
	 */
	public static final String PK_REGISTER = "pk_register";
	/**
	 * 登记单编号
	 */
	public static final String REGISTERNO = "registerno";

	public static final String SFFLAG = "sfflag";
	// 付款单位名称
	public static final String PAYUNITNAME = "payunitname";

	// BASEINFO
	public static final String PAYBANK = "paybank";

	public static final String PAYBANKACC = "paybankacc";

	public static final String ENDDATE = "enddate";

	public static final String RECEIVEBANK = "receivebank";

	public static final String ACCEPTANCENO = "acceptanceno";

	public static final String DISABLE = "disable";

	public static final String RECEIVEUNIT = "receiveunit";

	public static final String INVOICEDATE = "invoicedate";

	public static final String INVOICEUNIT = "invoiceunit";

	public static final String CONTRACTNO = "contractno";

	public static final String RECEIVEBANKACC = "receivebankacc";

	public static final String PK_CURR = "pk_curr";

	public static final String FBMBILLTYPE = "fbmbilltype";

	public static final String FBMBILLNO = "fbmbillno";

	public static final String PAYUNIT = "payunit";

	public static final String INVOICEUNITNAME = "invoiceunitname";

	public static final String ORIENTATION = "orientation";

	public static final String RECEIVEUNITNAME = "receiveunitname";

	public static final String RECEIVEACCNAME = "receiveaccname";


	public static final String VERIFYDATE = "verifydate";

	public static final String ISVERIFY = "isverify";

	public static final String VERIFYMAN = "verifyman";

	public static final String PK_LOANBANK = "pk_loanbank";

	public static final String PAYACCNAME = "payaccname";

	public static final String SECURITYMONEYF = "securitymoneyf";

	public static final String SECURITYMONEYB = "securitymoneyb";

	public static final String POUNDAGEMONEYF = "poundagemoneyf";

	public static final String POUNDAGEMONEYB = "poundagemoneyb";

	public static final String ISACCCUST = "isacccust";
	/**
	 * 收款单位银行账号编码
	 */
	public static final String RECEIVEBANKACCODE = "receivebankaccode";
	/**
	 * 付款单位银行账号编码
	 */
	public static final String PAYBANKACCODE = "paybankaccode";

	public static final String TXNLLFA = "txnllfa";// 贴现年利率方案 - in/no
	public static final String TXNLL = "txnlv";// 贴现年利率 - in/no
	public static final String TXYLL = "txyll";// 贴现月利率 - in/no
	public static final String TXRLL = "txrll";// 贴现日利率 in/no
	public static final String QXRQ = "qxrq";// 起效日期 - in/no
	public static final String TXRQ = "txrq";// 贴现日期 - in
	public static final String TXLX = "txlx";// 贴现利息 - out
	public static final String TXJZ = "txjz";// 贴现净值 - out
	public static final String LLTS = "llts";// 利率天数 - in
	public static final String TXTS = "txts";// 贴现天数 - in
	public static final String DISCOUNTDELAYDAYNUM = "discountdelaydaynum";// 贴现延迟天数
	// -
	// in
	public static final String ISRECACCCUST = "isrecacccust";
	public static final String ALL_CHOICE = "allchoice";
	public static final String CHOICE = "choice";

	/**
	 * 部门
	 */
	public static final String DEPT = "dept";

	public static final String VOUCHER = "voucher";

	public static final String VVOUCHERMANID = "vvouchermanid";

	public static final String DVOUCHERDATE = "dvoucherdate";

	public static final String INVOICEITEM = "invoiceitem"; // 开票收入项目

	public static final String INVOICEPLANITEM = "invoiceplanitem";// 开票计划项目

	public static final String CHARGEITEM = "chargitem";// 手续费支出项目

	public static final String CHARGEPLANITEM = "chargeplanitem";// 手续费计划项目

	public static final String PAYBANKNAME = "paybankname";// 付款银行名称

	public static final String RECEIVEBANKNAME = "receivebankname";// 收款银行名称

	public static final String GATHERPLANITEM = "gatherplanitem"; // 收票收入项目

	public static final String INVOICEOUTPLANITEM = "invoiceoutplanitem"; // 开票支出计划项目

	public static final String GATHERITEM = "gatheritem"; // 收票收支项目

	public static final String INVOICEOUTITEM = "invoiceoutitem"; // 付票收支项目
	
	public static final String FIRSTMAN = "firstman";//首次录入人
	
	public static final String APPROVETIME = "approvetime";//审核时间戳
	
	public static final String REGISTERSTATUS = "registerstatus";

	public Integer getDiscountdelaydaynum() {
		return discountdelaydaynum;
	}

	public void setDiscountdelaydaynum(Integer discountdelaydaynum) {
		this.discountdelaydaynum = discountdelaydaynum;
	}

	/**
	 * 属性def5的Getter方法. 说明:自定义项5
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法. 说明:自定义项5
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性pk_corp的Getter方法. 说明:公司
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法. 说明:公司
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性poundagemoney的Getter方法. 说明:手续费金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getPoundagemoney() {
		return poundagemoney;
	}

	/**
	 * 属性poundagemoney的Setter方法. 说明:手续费金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPoundagemoney
	 *            UFDouble
	 */
	public void setPoundagemoney(UFDouble newPoundagemoney) {

		poundagemoney = newPoundagemoney;
	}

	/**
	 * 属性cctype的Getter方法. 说明:授信类型
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getCctype() {
		return cctype;
	}

	/**
	 * 属性cctype的Setter方法. 说明:授信类型
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newCctype
	 *            String
	 */
	public void setCctype(String newCctype) {

		cctype = newCctype;
	}

	/**
	 * 属性keepunit的Getter方法. 说明:存放地点
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getKeepunit() {
		return keepunit;
	}

	/**
	 * 属性keepunit的Setter方法. 说明:存放地点
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newKeepunit
	 *            String
	 */
	public void setKeepunit(String newKeepunit) {

		keepunit = newKeepunit;
	}

	/**
	 * 属性voperatorid的Getter方法. 说明:操作人
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法. 说明:操作人
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性gathertype的Getter方法. 说明:收票来源类型
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getGathertype() {
		return gathertype;
	}

	/**
	 * 属性gathertype的Setter方法. 说明:收票来源类型
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newGathertype
	 *            String
	 */
	public void setGathertype(String newGathertype) {

		gathertype = newGathertype;
	}

	/**
	 * 属性vapprovenote的Getter方法. 说明:审核批语
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法. 说明:审核批语
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性brate的Getter方法. 说明:本币汇率
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getBrate() {
		return brate;
	}

	/**
	 * 属性brate的Setter方法. 说明:本币汇率
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newBrate
	 *            UFDouble
	 */
	public void setBrate(UFDouble newBrate) {

		brate = newBrate;
	}

	/**
	 * 属性vbillstatus的Getter方法. 说明:单据状态
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法. 说明:单据状态
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性holdunit的Getter方法. 说明:持票单位
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getHoldunit() {
		return holdunit;
	}

	/**
	 * 属性holdunit的Setter方法. 说明:持票单位
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newHoldunit
	 *            String
	 */
	public void setHoldunit(String newHoldunit) {

		holdunit = newHoldunit;
	}

	/**
	 * 属性pk_source的Getter方法. 说明:来源单据
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getPk_source() {
		return pk_source;
	}

	/**
	 * 属性pk_source的Setter方法. 说明:来源单据
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPk_source
	 *            String
	 */
	public void setPk_source(String newPk_source) {

		pk_source = newPk_source;
	}

	/**
	 * 属性pk_org的Getter方法. 说明:组织
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法. 说明:组织
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPk_org
	 *            String
	 */
	public void setPk_org(String newPk_org) {

		pk_org = newPk_org;
	}

	/**
	 * 属性frate的Getter方法. 说明:辅币汇率
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFrate() {
		return frate;
	}

	/**
	 * 属性frate的Setter方法. 说明:辅币汇率
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newFrate
	 *            UFDouble
	 */
	public void setFrate(UFDouble newFrate) {

		frate = newFrate;
	}

	/**
	 * 属性securityrate的Getter方法. 说明:保证金比例
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getSecurityrate() {
		return securityrate;
	}

	/**
	 * 属性securityrate的Setter方法. 说明:保证金比例
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newSecurityrate
	 *            UFDouble
	 */
	public void setSecurityrate(UFDouble newSecurityrate) {

		securityrate = newSecurityrate;
	}

	/**
	 * 属性moneyf的Getter方法. 说明:辅币金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyf() {
		return moneyf;
	}

	/**
	 * @return the baseinfoVo
	 */
	public BaseinfoVO getBaseinfoVo() {
		return baseinfoVo;
	}

	/**
	 * @param baseinfoVo
	 *            the baseinfoVo to set
	 */
	public void setBaseinfoVo(BaseinfoVO baseinfoVo) {
		this.baseinfoVo = baseinfoVo;
	}

	/**
	 * @return the pk_register
	 */
	public String getPk_register() {
		return pk_register;
	}

	/**
	 * @param pk_register
	 *            the pk_register to set
	 */
	public void setPk_register(String pk_register) {
		this.pk_register = pk_register;
	}

	/**
	 * 属性moneyf的Setter方法. 说明:辅币金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newMoneyf
	 *            UFDouble
	 */
	public void setMoneyf(UFDouble newMoneyf) {

		moneyf = newMoneyf;
	}

	/**
	 * 属性paybillunit的Getter方法. 说明:付票单位
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getPaybillunit() {
		return paybillunit;
	}

	/**
	 * 属性paybillunit的Setter方法. 说明:付票单位
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPaybillunit
	 *            String
	 */
	public void setPaybillunit(String newPaybillunit) {

		paybillunit = newPaybillunit;
	}

	/**
	 * 属性securitymoney的Getter方法. 说明:保证金金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getSecuritymoney() {
		return securitymoney;
	}

	/**
	 * 属性securitymoney的Setter方法. 说明:保证金金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newSecuritymoney
	 *            UFDouble
	 */
	public void setSecuritymoney(UFDouble newSecuritymoney) {

		securitymoney = newSecuritymoney;
	}

	/**
	 * 属性vbillno的Getter方法. 说明:单据编号
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法. 说明:单据编号
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性isnewbill的Getter方法. 说明:是否新票据
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFBoolean
	 */
	public UFBoolean getIsnewbill() {
		return isnewbill;
	}

	/**
	 * 属性isnewbill的Setter方法. 说明:是否新票据
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newIsnewbill
	 *            UFBoolean
	 */
	public void setIsnewbill(UFBoolean newIsnewbill) {

		isnewbill = newIsnewbill;
	}

	/**
	 * 属性impawnmode的Getter方法. 说明:担保方式
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getImpawnmode() {
		return impawnmode;
	}

	/**
	 * 属性impawnmode的Setter方法. 说明:担保方式
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newImpawnmode
	 *            String
	 */
	public void setImpawnmode(String newImpawnmode) {

		impawnmode = newImpawnmode;
	}

	/**
	 * 属性pk_baseinfo的Getter方法. 说明:票据基本信息
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getPk_baseinfo() {
		return pk_baseinfo;
	}

	/**
	 * 属性pk_baseinfo的Setter方法. 说明:票据基本信息
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPk_baseinfo
	 *            String
	 */
	public void setPk_baseinfo(String newPk_baseinfo) {

		pk_baseinfo = newPk_baseinfo;
	}

	/**
	 * 属性def1的Getter方法. 说明:自定义项1
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法. 说明:自定义项1
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性note的Getter方法. 说明:备注
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/**
	 * 属性note的Setter方法. 说明:备注
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newNote
	 *            String
	 */
	public void setNote(String newNote) {

		note = newNote;
	}

	/**
	 * 属性dapprovedate的Getter方法. 说明:审核日期
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法. 说明:审核日期
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性pk_billtypecode的Getter方法. 说明:单据类型
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法. 说明:单据类型
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPk_billtypecode
	 *            String
	 */
	public void setPk_billtypecode(String newPk_billtypecode) {

		pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性gatherdate的Getter方法. 说明:收票日期
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDate
	 */
	public UFDate getGatherdate() {
		return gatherdate;
	}

	/**
	 * 属性gatherdate的Setter方法. 说明:收票日期
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newGatherdate
	 *            UFDate
	 */
	public void setGatherdate(UFDate newGatherdate) {

		gatherdate = newGatherdate;
	}

	/**
	 * 属性vapproveid的Getter方法. 说明:审核人
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法. 说明:审核人
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法. 说明:自定义项2
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法. 说明:自定义项2
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性moneyy的Getter方法. 说明:票据金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyy() {
		return moneyy;
	}

	/**
	 * 属性moneyy的Setter方法. 说明:票据金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newMoneyy
	 *            UFDouble
	 */
	public void setMoneyy(UFDouble newMoneyy) {

		moneyy = newMoneyy;
	}

	/**
	 * 属性securityaccount的Getter方法. 说明:保证金账号
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getSecurityaccount() {
		return securityaccount;
	}

	/**
	 * 属性securityaccount的Setter方法. 说明:保证金账号
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newSecurityaccount
	 *            String
	 */
	public void setSecurityaccount(String newSecurityaccount) {

		securityaccount = newSecurityaccount;
	}

	/**
	 * 属性def4的Getter方法. 说明:自定义项4
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法. 说明:自定义项4
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性moneyb的Getter方法. 说明:本币金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyb() {
		return moneyb;
	}

	/**
	 * 属性moneyb的Setter方法. 说明:本币金额
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newMoneyb
	 *            UFDouble
	 */
	public void setMoneyb(UFDouble newMoneyb) {

		moneyb = newMoneyb;
	}

	/**
	 * 属性def3的Getter方法. 说明:自定义项3
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法. 说明:自定义项3
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性doperatedate的Getter方法. 说明:操作日期
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return UFDate
	 */
	public UFDate getDoperatedate() {
		return doperatedate;
	}

	/**
	 * 属性doperatedate的Setter方法. 说明:操作日期
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newDoperatedate
	 *            UFDate
	 */
	public void setDoperatedate(UFDate newDoperatedate) {

		doperatedate = newDoperatedate;
	}

	public UFBoolean getIsrecacccust() {
		return isrecacccust;
	}

	public void setIsrecacccust(UFBoolean isrecacccust) {
		this.isrecacccust = isrecacccust;
	}

	public BaseinfoVO getBaseinfoVO() {
		if (baseinfoVo == null) {
			baseinfoVo = new BaseinfoVO();
			baseinfoVo.setPaybank(paybank);
			baseinfoVo.setPaybankacc(paybankacc);
			baseinfoVo.setPayunit(payunit);
			baseinfoVo.setReceivebank(receivebank);
			baseinfoVo.setReceivebankacc(receivebankacc);
			baseinfoVo.setReceiveunit(receiveunit);
			baseinfoVo.setAcceptanceno(acceptanceno);
			baseinfoVo.setDisable(disable);
			baseinfoVo.setPk_billtypecode(pk_billtypecode);
			baseinfoVo.setInvoicedate(invoicedate);
			baseinfoVo.setInvoiceunit(invoiceunit);
			baseinfoVo.setMoneyy(moneyy);
			baseinfoVo.setContractno(contractno);
			baseinfoVo.setPk_curr(pk_curr);
			baseinfoVo.setPk_baseinfo(pk_baseinfo);
			baseinfoVo.setFbmbillno(fbmbillno);
			baseinfoVo.setFbmbilltype(fbmbilltype);
			baseinfoVo.setEnddate(enddate);
			baseinfoVo.setOrientation(orientation);
			baseinfoVo.setInvoiceunitname(invoiceunitname);
			baseinfoVo.setReceiveunitname(receiveunitname);
			baseinfoVo.setReceiveaccname(receiveaccname);
			baseinfoVo.setKeepunit(keepunit);
		}
		return baseinfoVo;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_register == null) {
			errFields.add(new String("pk_bill"));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("36201005", "UPP36201005-000015")/*
																											 * @res
																											 * "下列字段不能为空:"
																											 */);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-9-12
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-9-12
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_register";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-9-12
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return TABLENAME;
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2007-9-12
	 */
	public RegisterVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPk_register
	 *            主键值
	 */
	public RegisterVO(String newPk_register) {

		// 为主键字段赋值:
		pk_register = newPk_register;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_register;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @param newPk_register
	 *            String
	 */
	public void setPrimaryKey(String newPk_register) {

		pk_register = newPk_register;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2007-9-12
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return TABLENAME;

	}


	public String getPaybankacc() {
		return paybankacc;
	}

	public void setPaybankacc(String paybankacc) {
		this.paybankacc = paybankacc;
	}

	public String getPaybank() {
		return paybank;
	}

	public void setPaybank(String paybank) {
		this.paybank = paybank;
	}

	public UFDate getEnddate() {
		return enddate;
	}

	public void setEnddate(UFDate enddate) {
		this.enddate = enddate;
	}

	public String getReceivebank() {
		return receivebank;
	}

	public void setReceivebank(String receivebank) {
		this.receivebank = receivebank;
	}

	public String getAcceptanceno() {
		return acceptanceno;
	}

	public void setAcceptanceno(String acceptanceno) {
		this.acceptanceno = acceptanceno;
	}

	public UFBoolean getDisable() {
		return disable;
	}

	public void setDisable(UFBoolean disable) {
		this.disable = disable;
	}

	public String getFbmbilltype() {
		return fbmbilltype;
	}

	public void setFbmbilltype(String fbmbilltype) {
		this.fbmbilltype = fbmbilltype;
	}

	public String getPayunit() {
		return payunit;
	}

	public void setPayunit(String payunit) {
		this.payunit = payunit;
	}

	public String getReceiveunit() {
		return receiveunit;
	}

	public void setReceiveunit(String receiveunit) {
		this.receiveunit = receiveunit;
	}

	public UFDate getInvoicedate() {
		return invoicedate;
	}

	public void setInvoicedate(UFDate invoicedate) {
		this.invoicedate = invoicedate;
	}

	public String getInvoiceunit() {
		return invoiceunit;
	}

	public void setInvoiceunit(String invoiceunit) {
		this.invoiceunit = invoiceunit;
	}

	public String getContractno() {
		return contractno;
	}

	public void setContractno(String contractno) {
		this.contractno = contractno;
	}

	public String getReceivebankacc() {
		return receivebankacc;
	}

	public void setReceivebankacc(String receivebankacc) {
		this.receivebankacc = receivebankacc;
	}

	public String getPk_curr() {
		return pk_curr;
	}

	public void setPk_curr(String pk_curr) {
		this.pk_curr = pk_curr;
	}

	public String getFbmbillno() {
		return fbmbillno;
	}

	public void setFbmbillno(String fbmbillno) {
		this.fbmbillno = fbmbillno;
	}

	public String getReceiveunitname() {
		return receiveunitname;
	}

	public void setReceiveunitname(String receiveunitname) {
		this.receiveunitname = receiveunitname;
	}

	public String getReceiveaccname() {
		return receiveaccname;
	}

	public void setReceiveaccname(String receiveaccname) {
		this.receiveaccname = receiveaccname;
	}

	public String getOrientation() {
		return orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	public String getInvoiceunitname() {
		return invoiceunitname;
	}

	public void setInvoiceunitname(String invoiceunitname) {
		this.invoiceunitname = invoiceunitname;
	}

	public UFDouble getTxnlv() {
		return txnlv;
	}

	public void setTxnlv(UFDouble txnlv) {
		this.txnlv = txnlv;
	}

	public UFDouble getTxyll() {
		return txyll;
	}

	public void setTxyll(UFDouble txyll) {
		this.txyll = txyll;
	}

	public UFDouble getTxrll() {
		return txrll;
	}

	public void setTxrll(UFDouble txrll) {
		this.txrll = txrll;
	}

	public UFDate getQxrq() {
		return qxrq;
	}

	public void setQxrq(UFDate qxrq) {
		this.qxrq = qxrq;
	}

	public UFDate getTxrq() {
		return txrq;
	}

	public void setTxrq(UFDate txrq) {
		this.txrq = txrq;
	}

	public UFDouble getTxlx() {
		return txlx;
	}

	public void setTxlx(UFDouble txlx) {
		this.txlx = txlx;
	}

	public UFDouble getTxjz() {
		return txjz;
	}

	public void setTxjz(UFDouble txjz) {
		this.txjz = txjz;
	}

	public Integer getTxts() {
		return txts;
	}

	public void setTxts(Integer txts) {
		this.txts = txts;
	}

	public Integer getLlts() {
		return llts;
	}

	public void setLlts(Integer llts) {
		this.llts = llts;
	}

	public String getTxnllfa() {
		return txnllfa;
	}

	public void setTxnllfa(String txnllfa) {
		this.txnllfa = txnllfa;
	}

	public String getVerifyman() {
		return verifyman;
	}

	public void setVerifyman(String verifyman) {
		this.verifyman = verifyman;
	}

	public UFBoolean getIsverify() {
		return isverify;
	}

	public void setIsverify(UFBoolean isverify) {
		this.isverify = isverify;
	}

	public UFDate getVerifydate() {
		return verifydate;
	}

	public void setVerifydate(UFDate verifydate) {
		this.verifydate = verifydate;
	}

	public String getRegisterno() {
		return registerno;
	}

	public void setRegisterno(String registerno) {
		this.registerno = registerno;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public String getPk_loanbank() {
		return pk_loanbank;
	}

	public void setPk_loanbank(String pk_loanbank) {
		this.pk_loanbank = pk_loanbank;
	}

	public UFBoolean getSfflag() {
		return sfflag;
	}

	public void setSfflag(UFBoolean sfflag) {
		this.sfflag = sfflag;
	}

	public String getPayaccname() {
		return payaccname;
	}

	public void setPaybankname(String paybankname) {
		this.paybankname = paybankname;
	}

	public UFDouble getSecuritymoneyf() {
		return securitymoneyf;
	}

	public void setSecuritymoneyf(UFDouble securitymoneyf) {
		this.securitymoneyf = securitymoneyf;
	}

	public UFDouble getSecuritymoneyb() {
		return securitymoneyb;
	}

	public void setSecuritymoneyb(UFDouble securitymoneyb) {
		this.securitymoneyb = securitymoneyb;
	}

	public UFDouble getPoundagemoneyf() {
		return poundagemoneyf;
	}

	public void setPoundagemoneyf(UFDouble poundagemoneyf) {
		this.poundagemoneyf = poundagemoneyf;
	}

	public UFDouble getPoundagemoneyb() {
		return poundagemoneyb;
	}

	public void setPoundagemoneyb(UFDouble poundagemoneyb) {
		this.poundagemoneyb = poundagemoneyb;
	}

	public String getPayunitname() {
		return payunitname;
	}

	public void setPayunitname(String payunitname) {
		this.payunitname = payunitname;
	}

	public void setPayaccname(String payaccname) {
		this.payaccname = payaccname;
	}

	public UFBoolean getIsacccust() {
		return isacccust;
	}

	public void setIsacccust(UFBoolean isacccust) {
		this.isacccust = isacccust;
	}

	public String getPaybankaccode() {
		return paybankaccode;
	}

	public void setPaybankaccode(String paybankaccode) {
		this.paybankaccode = paybankaccode;
	}

	public String getReceivebankaccode() {
		return receivebankaccode;
	}

	public void setReceivebankaccode(String receivebankaccode) {
		this.receivebankaccode = receivebankaccode;
	}

	public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	/**
	 * <p>
	 * 交验当前VO,并记录VO错误 如果参数为null,只交验不记录错误
	 * <p>
	 * 作者：lisg <br>
	 * 日期：2006-9-8
	 * 
	 * @param errstr
	 * @return
	 */
	public boolean customValidate(StringBuffer errstr) {
		boolean ret = true;
		boolean recordit = true;
		if (errstr == null)
			recordit = false;

		if (this.txrq == null) {
			if (recordit) {
				errstr.append(NCLangRes4VoTransl.getNCLangRes().getStrByID("362004", "UPP362004-000153")
						+ "\n"/* 贴现日期不能为空 */);
			}
			ret = false;
		}

		if (this.llts == null) {
			if (recordit) {
				errstr.append(NCLangRes4VoTransl.getNCLangRes().getStrByID("362004", "UPP362004-000154")
						+ "\n"/* 利率天数不能为空 */);
			}
			ret = false;
		}

		if (this.txnllfa == null && this.txnlv == null) {
			if (recordit) {
				errstr.append(NCLangRes4VoTransl.getNCLangRes().getStrByID("362004", "UPP362004-000155")
						+ "\n"/* 贴现年利率方案和贴现年利率至少输入一项 */);
			}
			ret = false;
		}

		return ret;

	}

	public UFBoolean getChoice() {
		return choice;
	}

	public void setChoice(UFBoolean choice) {
		this.choice = choice;
	}

	public UFBoolean getVoucher() {
		return voucher;
	}

	public void setVoucher(UFBoolean voucher) {
		this.voucher = voucher;
	}

	public String getInvoiceitem() {
		return invoiceitem;
	}

	public void setInvoiceitem(String invoiceitem) {
		this.invoiceitem = invoiceitem;
	}

	public String getChargeitem() {
		return chargeitem;
	}

	public void setChargeitem(String chargeitem) {
		this.chargeitem = chargeitem;
	}

	public String getInvoiceplanitem() {
		return invoiceplanitem;
	}

	public void setInvoiceplanitem(String invoiceplanitem) {
		this.invoiceplanitem = invoiceplanitem;
	}

	public String getChargeplanitem() {
		return chargeplanitem;
	}

	public void setChargeplanitem(String chargeplanitem) {
		this.chargeplanitem = chargeplanitem;
	}

	public String getVvouchermanid() {
		return vvouchermanid;
	}

	public void setVvouchermanid(String vvouchermanid) {
		this.vvouchermanid = vvouchermanid;
	}

	public UFDate getDvoucherdate() {
		return dvoucherdate;
	}

	public void setDvoucherdate(UFDate dvoucherdate) {
		this.dvoucherdate = dvoucherdate;
	}


	public String getReceivebankname() {
		return receivebankname;
	}

	public void setReceivebankname(String receivebankname) {
		this.receivebankname = receivebankname;
	}

	public String getPaybankname() {
		return paybankname;
	}

	public String getGatherplanitem() {
		return gatherplanitem;
	}

	public void setGatherplanitem(String gatherplanitem) {
		this.gatherplanitem = gatherplanitem;
	}

	public String getInvoiceoutplanitem() {
		return invoiceoutplanitem;
	}

	public void setInvoiceoutplanitem(String invoiceoutplanitem) {
		this.invoiceoutplanitem = invoiceoutplanitem;
	}

	public String getGatheritem() {
		return gatheritem;
	}

	public void setGatheritem(String gatheritem) {
		this.gatheritem = gatheritem;
	}

	public String getInvoiceoutitem() {
		return invoiceoutitem;
	}

	public void setInvoiceoutitem(String invoiceoutitem) {
		this.invoiceoutitem = invoiceoutitem;
	}

	public UFBoolean getWritebankacc() {
		return writebankacc;
	}

	public void setWritebankacc(UFBoolean writebankacc) {
		this.writebankacc = writebankacc;
	}

	public UFBoolean getWriteinneracc() {
		return writeinneracc;
	}

	public void setWriteinneracc(UFBoolean writeinneracc) {
		this.writeinneracc = writeinneracc;
	}

	public String getFirstman() {
		return firstman;
	}

	public void setFirstman(String firstman) {
		this.firstman = firstman;
	}

	public UFDateTime getApprovetime() {
		return approvetime;
	}

	public void setApprovetime(UFDateTime approvetime) {
		this.approvetime = approvetime;
	}

	public String getRegisterstatus() {
		return registerstatus;
	}

	public void setRegisterstatus(String registerstatus) {
		this.registerstatus = registerstatus;
	}
	
	public UFBoolean getWriteplan() {
		return writeplan;
	}

	public void setWriteplan(UFBoolean writeplan) {
		this.writeplan = writeplan;
	}
	
}