/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fbm.storage;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2007-8-20
 * 
 * @author author
 * @version Your Project 1.0
 */
public class StorageVO extends SuperVO {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	public static String tablecode = "fbm_storage";
	public static final String Procmsg_flag = "_";// 提供给凭证使用，构造业务PK

	public String def5;
	public String vbillno;
	public String inputperson;
	public String keepunit;
	public String def1;
	public String voperatorid;
	public String outputperson;
	public String vapprovenote;
	public String pk_storage;
	public UFDate dapprovedate;
	public String pk_billtypecode;
	public Integer vbillstatus;
	public UFDate outputdate;
	public String vapproveid;
	public String def2;
	public UFDate inputdate;
	public String inputtype;
	public String def4;
	public String def3;
	public UFDate doperatedate;
	public String pk_corp;
	public UFDateTime ts;
	public Integer dr;
	// 提供给中心入库使用
	public String returnperson;
	public UFDate returndate;
	public String keepaccount;
	public String returnreason;
	public String memo;
	public String outputunit;
	// public String outputaccount;
	public StoragePowerVO powerVo;
	public String vvouchermanid;
	public UFDate vvoucherdate;
	public String unitvouchermanid;
	public UFDate unitvoucherdate;

	public String pk_accidcurr;// 表头上的币种字段

	public String pk_currtype;// 币种
	public UFDouble discountinterest;// 贴现利息
	public UFBoolean unittally;// 单位记账
	public UFBoolean unitvoucher;// 单位制证
	public UFBoolean centervoucher;// 中心制证

	public UFDouble summoneyy;// 托管金额
	public String submitmanid;// 提交人
	public UFDate submitdate;// 提交日期
	public String pk_bankdoc;// 受托银行

	public String keepcorp;// 托管公司
	public UFDate dealdate;// 受理日期
	public String tallyman;// 记账人
	public UFDate tallydate;// 记账日期
	public String businessno;// 业务流水号
	public String unitplanitem;// 单位计划项目
	public String unititem;// 单位项目
	/**
	 * 临时变量，保存是否要回写计划,true：回写；null || false：不回写
	 */
	private UFBoolean writePlan;

	private UFBoolean writebankacc;

	private UFBoolean writeinneracc;

	public static final String PK_CORP = "pk_corp";
	public static final String TS = "ts";
	public static final String DR = "dr";
	public static final String DEF5 = "def5";
	public static final String VBILLNO = "vbillno";
	public static final String INPUTPERSON = "inputperson";
	public static final String KEEPUNIT = "keepunit";
	public static final String DEF1 = "def1";
	public static final String VOPERATORID = "voperatorid";
	public static final String OUTPUTPERSON = "outputperson";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String PK_STORAGE = "pk_storage";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String OUTPUTDATE = "outputdate";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DEF2 = "def2";
	public static final String INPUTDATE = "inputdate";
	public static final String INPUTTYPE = "inputtype";
	public static final String DEF4 = "def4";
	public static final String DEF3 = "def3";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String RETURNPERSON = "returnperson";
	public static final String RETURNDATE = "returndate";
	public static final String KEEPACCOUNT = "keepaccount";
	public static final String RETURNREASON = "returnreason";
	public static final String OUTPUTUNIT = "outputunit";
	public static final String MEMO = "memo";
	public static final String VVOUCHERMANID = "vvouchermanid";
	public static final String VVOUCHERDATE = "vvoucherdate";
	public static final String PK_ACCIDCURR = "pk_accidcurr";
	public static final String UNITVOUCHERMANID = "unitvouchermanid";
	public static final String UNITVOUCHERDATE = "unitvoucherdate";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String DISCOUNTINTEREST = "discountinterest";

	public static final String UNITTALLY = "unittally";
	public static final String UNITVOUCHER = "unitvoucher";
	public static final String CENTERVOUCHER = "centervoucher";
	public static final String SUMMONEYY = "summoneyy";
	public static final String SUBMITMANID = "submitmanid";
	public static final String SUBMITDATE = "submitdate";
	public static final String PK_BANKDOC = "pk_bankdoc";
	public static final String KEEPCORP = "keepcorp";
	public static final String DEALDATE = "dealdate";
	public static final String TALLYMAN = "tallyman";
	public static final String TALLYDATE = "tallydate";
	public static final String UNITPLANITEM = "unitplanitem";
	public static final String UNITITEM = "unititem";

	public String getPk_currtype() {
		return pk_currtype;
	}

	public void setPk_currtype(String pk_currtype) {
		this.pk_currtype = pk_currtype;
	}

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性inputperson的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getInputperson() {
		return inputperson;
	}

	public String getOutputperson() {
		return outputperson;
	}

	public void setOutputperson(String outputperson) {
		this.outputperson = outputperson;
	}

	public void setInputperson(String inputperson) {
		this.inputperson = inputperson;
	}

	/**
	 * 属性keepunit的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getKeepunit() {
		return keepunit;
	}

	/**
	 * 属性keepunit的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newKeepunit
	 *            String
	 */
	public void setKeepunit(String newKeepunit) {

		keepunit = newKeepunit;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性pk_storage的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getPk_storage() {
		return pk_storage;
	}

	/**
	 * 属性pk_storage的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newPk_storage
	 *            String
	 */
	public void setPk_storage(String newPk_storage) {

		pk_storage = newPk_storage;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性pk_billtypecode的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newPk_billtypecode
	 *            String
	 */
	public void setPk_billtypecode(String newPk_billtypecode) {

		pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性outputdate的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return UFDate
	 */
	public UFDate getOutputdate() {
		return outputdate;
	}

	/**
	 * 属性outputdate的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newOutputdate
	 *            UFDate
	 */
	public void setOutputdate(UFDate newOutputdate) {

		outputdate = newOutputdate;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性inputdate的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return UFDate
	 */
	public UFDate getInputdate() {
		return inputdate;
	}

	/**
	 * 属性inputdate的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newInputdate
	 *            UFDate
	 */
	public void setInputdate(UFDate newInputdate) {

		inputdate = newInputdate;
	}

	/**
	 * 属性inputtype的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getInputtype() {
		return inputtype;
	}

	/**
	 * 属性inputtype的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newInputtype
	 *            String
	 */
	public void setInputtype(String newInputtype) {

		inputtype = newInputtype;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性doperatedate的Getter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return UFDate
	 */
	public UFDate getDoperatedate() {
		return doperatedate;
	}

	/**
	 * 属性doperatedate的Setter方法.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newDoperatedate
	 *            UFDate
	 */
	public void setDoperatedate(UFDate newDoperatedate) {

		doperatedate = newDoperatedate;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public String getReturnperson() {
		return returnperson;
	}

	public void setReturnperson(String returnperson) {
		this.returnperson = returnperson;
	}

	public UFDate getReturndate() {
		return returndate;
	}

	public void setReturndate(UFDate returndate) {
		this.returndate = returndate;
	}

	public String getKeepaccount() {
		return keepaccount;
	}

	public void setKeepaccount(String keepaccount) {
		this.keepaccount = keepaccount;
	}

	public String getReturnreason() {
		return returnreason;
	}

	public void setReturnreason(String returnreason) {
		this.returnreason = returnreason;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getOutputunit() {
		return outputunit;
	}

	public void setOutputunit(String outputunit) {
		this.outputunit = outputunit;
	}

	public String getVvouchermanid() {
		return vvouchermanid;
	}

	public void setVvouchermanid(String vvouchermanid) {
		this.vvouchermanid = vvouchermanid;
	}

	public UFDate getVvoucherdate() {
		return vvoucherdate;
	}

	public void setVvoucherdate(UFDate vvoucherdate) {
		this.vvoucherdate = vvoucherdate;
	}

	public StoragePowerVO getPowerVo() {
		return powerVo;
	}

	public void setPowerVo(StoragePowerVO powerVo) {
		this.powerVo = powerVo;
	}

	public String getPk_accidcurr() {
		return pk_accidcurr;
	}

	public void setPk_accidcurr(String pk_accidcurr) {
		this.pk_accidcurr = pk_accidcurr;
	}

	public String getUnitvouchermanid() {
		return unitvouchermanid;
	}

	public void setUnitvouchermanid(String unitvouchermanid) {
		this.unitvouchermanid = unitvouchermanid;
	}

	public UFDate getUnitvoucherdate() {
		return unitvoucherdate;
	}

	public void setUnitvoucherdate(UFDate unitvoucherdate) {
		this.unitvoucherdate = unitvoucherdate;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_storage == null) {
			errFields.add(new String("pk_storage"));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("36201010", "UPP36201010-000012")/*
																											 * @res
																											 * "下列字段不能为空:"
																											 */);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-8-20
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-8-20
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_storage";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-8-20
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_storage";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2007-8-20
	 */
	public StorageVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newPk_storage
	 *            主键值
	 */
	public StorageVO(String newPk_storage) {

		// 为主键字段赋值:
		pk_storage = newPk_storage;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_storage;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @param newPk_storage
	 *            String
	 */
	public void setPrimaryKey(String newPk_storage) {

		pk_storage = newPk_storage;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2007-8-20
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_storage";

	}

	public UFDouble getDiscountinterest() {
		return discountinterest;
	}

	public void setDiscountinterest(UFDouble discountinterest) {
		this.discountinterest = discountinterest;
	}

	public UFBoolean getUnittally() {
		return unittally;
	}

	public void setUnittally(UFBoolean unittally) {
		this.unittally = unittally;
	}

	public UFBoolean getUnitvoucher() {
		return unitvoucher;
	}

	public void setUnitvoucher(UFBoolean unitvoucher) {
		this.unitvoucher = unitvoucher;
	}

	public UFBoolean getCentervoucher() {
		return centervoucher;
	}

	public void setCentervoucher(UFBoolean centervoucher) {
		this.centervoucher = centervoucher;
	}

	public UFDouble getSummoneyy() {
		return summoneyy;
	}

	public void setSummoneyy(UFDouble summoneyy) {
		this.summoneyy = summoneyy;
	}

	public String getSubmitmanid() {
		return submitmanid;
	}

	public void setSubmitmanid(String submitmanid) {
		this.submitmanid = submitmanid;
	}

	public UFDate getSubmitdate() {
		return submitdate;
	}

	public void setSubmitdate(UFDate submitdate) {
		this.submitdate = submitdate;
	}

	public String getPk_bankdoc() {
		return pk_bankdoc;
	}

	public void setPk_bankdoc(String pk_bankdoc) {
		this.pk_bankdoc = pk_bankdoc;
	}

	public String getKeepcorp() {
		return keepcorp;
	}

	public void setKeepcorp(String keepcorp) {
		this.keepcorp = keepcorp;
	}

	public UFDate getDealdate() {
		return dealdate;
	}

	public void setDealdate(UFDate dealdate) {
		this.dealdate = dealdate;
	}

	public String getTallyman() {
		return tallyman;
	}

	public void setTallyman(String tallyman) {
		this.tallyman = tallyman;
	}

	public UFDate getTallydate() {
		return tallydate;
	}

	public void setTallydate(UFDate tallydate) {
		this.tallydate = tallydate;
	}

	public String getBusinessno() {
		return businessno;
	}

	public void setBusinessno(String businessno) {
		this.businessno = businessno;
	}

	public String getUnitplanitem() {
		return unitplanitem;
	}

	public void setUnitplanitem(String unitplanitem) {
		this.unitplanitem = unitplanitem;
	}

	public String getUnititem() {
		return unititem;
	}

	public void setUnititem(String unititem) {
		this.unititem = unititem;
	}

	public UFBoolean getWritePlan() {
		return writePlan;
	}

	public void setWritePlan(UFBoolean writePlan) {
		this.writePlan = writePlan;
	}

	public UFBoolean getWritebankacc() {
		return writebankacc;
	}

	public void setWritebankacc(UFBoolean writebankacc) {
		this.writebankacc = writebankacc;
	}

	public UFBoolean getWriteinneracc() {
		return writeinneracc;
	}

	public void setWriteinneracc(UFBoolean writeinneracc) {
		this.writeinneracc = writeinneracc;
	}

}