/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
 \***************************************************************/
package nc.vo.fbm.pub;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;

/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2007-8-8
 *
 * @author author
 * @version Your Project 1.0
 */
public class ActionVO extends SuperVO {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	public Integer serialnum;

	public String beginstatus;

	public String endstatus;

	public String actionperson;

	public String pk_bill;//操作业务单据PK

	public String pk_action;

	public String billtype;

	public UFDate actiondate;

	public String actioncode;

	public String pk_source;//收票登记单PK

	public String pk_baseinfo;//票据基本信息PK

	public String pk_org;//组织

	public UFBoolean isnew;

	public String pk_corp;

	public Integer dr;

	public UFDateTime ts;


	public static final String BEGINSTATUS = "beginstatus";

	public static final String ENDSTATUS = "endstatus";

	public static final String ACTIONPERSON = "actionperson";

	public static final String PK_BILL = "pk_bill";

	public static final String PK_ACTION = "pk_action";

	public static final String BILLTYPE = "billtype";

	public static final String PK_BASEINFO = "pk_baseinfo";

	public static final String ACTIONDATE = "actiondate";

	public static final String ACTIONCODE = "actioncode";

	/**
	 * 属性serialno的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return Integer
	 */
//	public String getSerialno() {
//		return serialno;
//	}
//
//	/**
//	 * 属性serialno的Setter方法.
//	 *
//	 * 创建日期:2007-8-8
//	 *
//	 * @param newSerialno
//	 *            Integer
//	 */
//	public void setSerialno(String newSerialno) {
//
//		serialno = newSerialno;
//	}

	/**
	 * 属性beginstatus的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return Integer
	 */
	public String getBeginstatus() {
		return beginstatus;
	}

	/**
	 * 属性beginstatus的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newBeginstatus
	 *            Integer
	 */
	public void setBeginstatus(String newBeginstatus) {

		beginstatus = newBeginstatus;
	}

	/**
	 * 属性actionperson的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getActionperson() {
		return actionperson;
	}

	/**
	 * 属性actionperson的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newActionperson
	 *            String
	 */
	public void setActionperson(String newActionperson) {

		actionperson = newActionperson;
	}

	/**
	 * 属性pk_bill的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPk_bill() {
		return pk_bill;
	}

	/**
	 * 属性pk_bill的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_bill
	 *            String
	 */
	public void setPk_bill(String newPk_bill) {

		pk_bill = newPk_bill;
	}

	/**
	 * 属性pk_action的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPk_action() {
		return pk_action;
	}

	/**
	 * 属性pk_action的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_action
	 *            String
	 */
	public void setPk_action(String newPk_action) {

		pk_action = newPk_action;
	}

	/**
	 * 属性billtype的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getBilltype() {
		return billtype;
	}

	/**
	 * 属性billtype的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newBilltype
	 *            String
	 */
	public void setBilltype(String newBilltype) {

		billtype = newBilltype;
	}


	/**
	 * 属性actiondate的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return UFDate
	 */
	public UFDate getActiondate() {
		return actiondate;
	}

	/**
	 * 属性actiondate的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newActiondate
	 *            UFDate
	 */
	public void setActiondate(UFDate newActiondate) {

		actiondate = newActiondate;
	}

	/**
	 * 属性actioncode的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getActioncode() {
		return actioncode;
	}

	/**
	 * 属性actioncode的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newActioncode
	 *            String
	 */
	public void setActioncode(String newActioncode) {

		actioncode = newActioncode;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_action == null) {
			errFields.add(new String("pk_action"));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("fbmcomm","UPPFBMComm-000385")/* @res"下列字段不能为空:"*/);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "pk_gather";

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_action";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_action";
	}

	/**
	 * 按照默认方式创建构造子.
	 *
	 * 创建日期:2007-8-8
	 */
	public ActionVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_action
	 *            主键值
	 */
	public ActionVO(String newPk_action) {

		// 为主键字段赋值:
		pk_action = newPk_action;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_action;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_action
	 *            String
	 */
	public void setPrimaryKey(String newPk_action) {

		pk_action = newPk_action;

	}

	/**
	 * 返回数值对象的显示名称.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_action";

	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public String getEndstatus() {
		return endstatus;
	}

	public void setEndstatus(String endstatus) {
		this.endstatus = endstatus;
	}

	public String getPk_source() {
		return pk_source;
	}

	public void setPk_source(String pk_source) {
		this.pk_source = pk_source;
	}

	public UFBoolean getIsnew() {
		return isnew;
	}

	public void setIsnew(UFBoolean isnew) {
		this.isnew = isnew;
	}

	public String getPk_baseinfo() {
		return pk_baseinfo;
	}

	public void setPk_baseinfo(String pk_baseinfo) {
		this.pk_baseinfo = pk_baseinfo;
	}

	public String getPk_org() {
		return pk_org;
	}

	public void setPk_org(String pk_org) {
		this.pk_org = pk_org;
	}

	public Integer getSerialnum() {
		return serialnum;
	}

	public void setSerialnum(Integer serialnum) {
		this.serialnum = serialnum;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}





}