/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
 \***************************************************************/
package nc.vo.fbm.pub;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2007-8-8
 *
 * @author author
 * @version Your Project 1.0
 */
public class BaseinfoVO extends SuperVO {

	//付款单位银行账号
	public String paybankacc;

	//付款银行
	public String paybank;

	//到期日期
	public UFDate enddate;

	//收款银行
	public String receivebank;

	//承兑协议编号
	public String acceptanceno;

	//废票标志
	public UFBoolean disable;

	//主键
	public String pk_baseinfo;

	//
	public String pk_billtypecode;

	//付款单位
	public String payunit;

	//存放地点
	public String keepunit;

	//收票日期
	public UFDate receivedate;

	//收款单位
	public String receiveunit;

	//出票日期
	public UFDate invoicedate;

	//出票人全称
	public String invoiceunit;

	//汇票金额
	public UFDouble moneyy;

	//票据编号
	public String fbmbillno;

	//票据类型
	public String fbmbilltype;

	//交易合同编号
	public String contractno;

	//收款单位银行账号
	public String receivebankacc;

	//币种
	public String pk_curr;


	public String receiveunitname;

	public String receiveaccname;

	public String orientation;

	public String invoiceunitname;

	public Integer dr;

	public UFDateTime ts;
	
	public String baseinfostatus;

	public static final String INVOICEUNITNAME="invoiceunitname";

	public static final String ORIENTATION="orientation";

	public static final String RECEIVEUNITNAME="receiveunitname";

	public static final String RECEIVEACCNAME="receiveaccname";

	public static final String FBMBILLTYPE="fbmbilltype";

	public static final String PAYBANKACC = "paybankacc";

	public static final String PAYBANK = "paybank";

	public static final String ENDDATE = "enddate";

	public static final String RECEIVEBANK = "receivebank";

	public static final String ACCEPTANCENO = "acceptanceno";

	public static final String DISABLE = "disable";

	public static final String PK_BASEINFO = "pk_baseinfo";

	public static final String PK_BILLTYPECODE = "pk_billtypecode";

	public static final String PAYUNIT = "payunit";

	public static final String KEEPUNIT = "keepunit";

	public static final String RECEIVEDATE = "receivedate";

	public static final String RECEIVEUNIT = "receiveunit";

	public static final String INVOICEDATE = "invoicedate";

	public static final String INVOICEUNIT = "invoiceunit";

	public static final String MONEYY = "moneyy";

	public static final String FBMBILLNO = "fbmbillno";

	public static final String CONTRACTNO = "contractno";

	public static final String RECEIVEBANKACC = "receivebankacc";

	public static final String PK_CURR = "pk_curr";
	
	public static final String BASEINFOSTATUS = "baseinfostatus";
	

	/**
	 * 属性paybankacc的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPaybankacc() {
		return paybankacc;
	}

	/**
	 * 属性paybankacc的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPaybankacc
	 *            String
	 */
	public void setPaybankacc(String newPaybankacc) {

		paybankacc = newPaybankacc;
	}

	/**
	 * 属性paybank的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPaybank() {
		return paybank;
	}

	/**
	 * 属性paybank的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPaybank
	 *            String
	 */
	public void setPaybank(String newPaybank) {

		paybank = newPaybank;
	}

	/**
	 * 属性enddate的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return UFDate
	 */
	public UFDate getEnddate() {
		return enddate;
	}

	/**
	 * 属性enddate的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newEnddate
	 *            UFDate
	 */
	public void setEnddate(UFDate newEnddate) {

		enddate = newEnddate;
	}

	/**
	 * 属性receivebank的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getReceivebank() {
		return receivebank;
	}

	/**
	 * 属性receivebank的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newReceivebank
	 *            String
	 */
	public void setReceivebank(String newReceivebank) {

		receivebank = newReceivebank;
	}

	/**
	 * 属性acceptanceno的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getAcceptanceno() {
		return acceptanceno;
	}

	/**
	 * 属性acceptanceno的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newAcceptanceno
	 *            String
	 */
	public void setAcceptanceno(String newAcceptanceno) {

		acceptanceno = newAcceptanceno;
	}

	/**
	 * 属性disable的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return UFBoolean
	 */
	public UFBoolean getDisable() {
		return disable;
	}

	/**
	 * 属性disable的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newDisable
	 *            UFBoolean
	 */
	public void setDisable(UFBoolean newDisable) {

		disable = newDisable;
	}

	/**
	 * 属性pk_baseinfo的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPk_baseinfo() {
		return pk_baseinfo;
	}

	/**
	 * 属性pk_baseinfo的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_baseinfo
	 *            String
	 */
	public void setPk_baseinfo(String newPk_baseinfo) {

		pk_baseinfo = newPk_baseinfo;
	}



	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	public void setPk_billtypecode(String pk_billtypecode) {
		this.pk_billtypecode = pk_billtypecode;
	}

	/**
	 * 属性payunit的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPayunit() {
		return payunit;
	}

	/**
	 * 属性payunit的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPayunit
	 *            String
	 */
	public void setPayunit(String newPayunit) {

		payunit = newPayunit;
	}

	/**
	 * 属性keepunit的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getKeepunit() {
		return keepunit;
	}

	/**
	 * 属性keepunit的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newKeepunit
	 *            String
	 */
	public void setKeepunit(String newKeepunit) {

		keepunit = newKeepunit;
	}

	/**
	 * 属性receivedate的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return UFDate
	 */
	public UFDate getReceivedate() {
		return receivedate;
	}

	/**
	 * 属性receivedate的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newReceivedate
	 *            UFDate
	 */
	public void setReceivedate(UFDate newReceivedate) {

		receivedate = newReceivedate;
	}

	/**
	 * 属性receiveunit的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getReceiveunit() {
		return receiveunit;
	}

	/**
	 * 属性receiveunit的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newReceiveunit
	 *            String
	 */
	public void setReceiveunit(String newReceiveunit) {

		receiveunit = newReceiveunit;
	}

	/**
	 * 属性invoicedate的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return UFDate
	 */
	public UFDate getInvoicedate() {
		return invoicedate;
	}

	/**
	 * 属性invoicedate的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newInvoicedate
	 *            UFDate
	 */
	public void setInvoicedate(UFDate newInvoicedate) {

		invoicedate = newInvoicedate;
	}

	/**
	 * 属性invoiceunit的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getInvoiceunit() {
		return invoiceunit;
	}

	/**
	 * 属性invoiceunit的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newInvoiceunit
	 *            String
	 */
	public void setInvoiceunit(String newInvoiceunit) {

		invoiceunit = newInvoiceunit;
	}

	/**
	 * 属性moneyy的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return UFDouble
	 */
	public UFDouble getMoneyy() {
		return moneyy;
	}

	/**
	 * 属性moneyy的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newMoneyy
	 *            UFDouble
	 */
	public void setMoneyy(UFDouble newMoneyy) {

		moneyy = newMoneyy;
	}

	/**
	 * 属性fbmbillno的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getFbmbillno() {
		return fbmbillno;
	}

	/**
	 * 属性fbmbillno的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newFbmbillno
	 *            String
	 */
	public void setFbmbillno(String newFbmbillno) {

		fbmbillno = newFbmbillno;
	}

	/**
	 * 属性contractno的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getContractno() {
		return contractno;
	}

	/**
	 * 属性contractno的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newContractno
	 *            String
	 */
	public void setContractno(String newContractno) {

		contractno = newContractno;
	}

	/**
	 * 属性receivebankacc的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getReceivebankacc() {
		return receivebankacc;
	}

	/**
	 * 属性receivebankacc的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newReceivebankacc
	 *            String
	 */
	public void setReceivebankacc(String newReceivebankacc) {

		receivebankacc = newReceivebankacc;
	}

	/**
	 * 属性pk_curr的Getter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPk_curr() {
		return pk_curr;
	}

	/**
	 * 属性pk_curr的Setter方法.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_curr
	 *            String
	 */
	public void setPk_curr(String newPk_curr) {

		pk_curr = newPk_curr;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_baseinfo == null) {
			errFields.add(new String("pk_baseinfo"));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("fbmcomm","UPPFBMComm-000385")/* @res"下列字段不能为空:"*/);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "pk_gather";

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_baseinfo";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_baseinfo";
	}

	/**
	 * 按照默认方式创建构造子.
	 *
	 * 创建日期:2007-8-8
	 */
	public BaseinfoVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_baseinfo
	 *            主键值
	 */
	public BaseinfoVO(String newPk_baseinfo) {

		// 为主键字段赋值:
		pk_baseinfo = newPk_baseinfo;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_baseinfo;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @param newPk_baseinfo
	 *            String
	 */
	public void setPrimaryKey(String newPk_baseinfo) {

		pk_baseinfo = newPk_baseinfo;

	}

	/**
	 * 返回数值对象的显示名称.
	 *
	 * 创建日期:2007-8-8
	 *
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_baseinfo";

	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public String getFbmbilltype() {
		return fbmbilltype;
	}

	public void setFbmbilltype(String fbmbilltype) {
		this.fbmbilltype = fbmbilltype;
	}

	public String getReceiveunitname() {
		return receiveunitname;
	}

	public void setReceiveunitname(String receiveunitname) {
		this.receiveunitname = receiveunitname;
	}

	public String getReceiveaccname() {
		return receiveaccname;
	}

	public void setReceiveaccname(String receiveaccname) {
		this.receiveaccname = receiveaccname;
	}

	public String getOrientation() {
		return orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	public String getInvoiceunitname() {
		return invoiceunitname;
	}

	public void setInvoiceunitname(String invoiceunitname) {
		this.invoiceunitname = invoiceunitname;
	}

	public String getBaseinfostatus() {
		return baseinfostatus;
	}

	public void setBaseinfostatus(String baseinfostatus) {
		this.baseinfostatus = baseinfostatus;
	}
	
	
}