/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fbm.consignbank;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 票据银行托收VO类
 * </p>
 * 
 * 创建日期:2007-8-22
 * 
 * @author author bsrl
 * @version Project 5.02
 */
public class CollectionVO extends SuperVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public String collectionno;
	public String def5;
	public String pk_corp;
	public String pk_baseinfo;
	public UFDate ddisabledate;
	public String voperatorid;
	public UFDouble brate;
	public String vapprovenote;
	public UFDate dtransactdate;
	public Integer vbillstatus;
	public String pk_source;
	public String pk_org;
	public UFDouble frate;
	public String vdisablemanid;
	public UFDouble moneyf;
	public String vbillno;
	public String vtransactorid;
	public UFDate dcollectiondate;
	public String def1;
	public String disablenote;
	public String note;
	public String pk_billtypecode;
	public UFDate dapprovedate;
	public String pk_collection;
	public String vapproveid;
	public String def2;
	public UFDouble moneyy;
	public UFDate dconsigndate;
	public String def4;
	public UFDouble moneyb;
	public String def3;
	public UFDate doperatedate;
	public Integer dr;
	public UFDateTime ts;
	public String holderacc;
	public String pk_holderbank;
	// 操作类型:0->私有；1->统管
	public String opbilltype;
	// 制证人
	public String vvoucherid;
	// 制证日期
	public UFDate dvoucherdate;

	public String pjlx;
	public String fkdw;
	public String fkkhh;
	public String fkdwyhzh;
	public String cprmc;
	public String ybbz;
	public UFDouble pmje;
	public UFDate cprq;
	public UFDate dqrq;
	public UFDate sprq;
	public String receiveunit;
	public String receivebankacc;
	public UFBoolean unitvoucher;
	// public String fbillstatus;

	// add by wangyg 修改托收单制证后联查凭证时票据编号显示的是PK,而不是编号的问题
	private String fbmbillno; // 票据编号

	private String collectionitem;// 托收收支项目
	private String collectionplanitem;// 托收计划项目
	private String fbmplanitem;// 应收票据支出计划项目
	private String fbmitem;// 应收票据支出项目
	/**
	 * 临时变量，保存是否要回写计划,true：回写；null || false：不回写
	 */
	private UFBoolean writeplan;

	private UFBoolean writebankacc;

	private UFBoolean writeinneracc;

	public static final String COLLECTIONPLANITEM = "collectionplanitem";
	public static final String PK_CURR = "pk_curr";
	public static final String RECEIVEUNIT = "receiveunit";
	public static final String RECEIVEBANKACC = "receivebankacc";
	public static final String COLLECTIONNO = "collectionno";
	public static final String DEF5 = "def5";
	public static final String PK_CORP = "pk_corp";
	public static final String DDISABLEDATE = "ddisabledate";
	public static final String VOPERATORID = "voperatorid";
	public static final String BRATE = "brate";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String DTRANSACTDATE = "dtransactdate";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String PK_SOURCE = "pk_source";
	public static final String PK_ORG = "pk_org";
	public static final String FRATE = "frate";
	public static final String VDISABLEMANID = "vdisablemanid";
	public static final String MONEYF = "moneyf";
	public static final String VBILLNO = "vbillno";
	public static final String VTRANSACTORID = "vtransactorid";
	public static final String DCOLLECTIONDATE = "dcollectiondate";
	public static final String DEF1 = "def1";
	public static final String DISABLENOTE = "disablenote";
	public static final String NOTE = "note";
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String PK_COLLECTION = "pk_collection";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DEF2 = "def2";
	public static final String MONEYY = "moneyy";
	public static final String DCONSIGNDATE = "dconsigndate";
	public static final String DEF4 = "def4";
	public static final String MONEYB = "moneyb";
	public static final String DEF3 = "def3";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String HOLDERACC = "holderacc";
	public static final String HOLDERBANK = "pk_holderbank";
	public static final String PK_BASEINFO = "pk_baseinfo";

	public static final String FKDW = "fkdw";
	public static final String FKKHH = "fkkhh";
	public static final String FKDWYHZH = "fkdwyhzh";
	public static final String CPRMC = "cprmc";
	public static final String YBBZ = "ybbz";
	public static final String PMJE = "pmje";
	public static final String CPRQ = "cprq";
	public static final String DQRQ = "dqrq";
	public static final String PJLX = "pjlx";
	public static final String SPRQ = "sprq";
	// public static final String FBILLSTATUS="fbillstatus";
	public static final String OPBILLTYPE = "opbilltype";
	public static final String VVOUCHERID = "vvoucherid";
	public static final String DVOUCHERDATE = "dvoucherdate";

	public static final String FBMBILLNO = "fbmbillno";// 票据编号
	public static final String UNITVOUCHER = "unitvoucher";
	public static final String FBMPLANITEM = "fbmplanitem";
	public static final String FBMITEM = "fbmitem";

	public UFDate getSprq() {
		return sprq;
	}

	public void setSprq(UFDate sprq) {
		this.sprq = sprq;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性ddisabledate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDate
	 */
	public UFDate getDdisabledate() {
		return ddisabledate;
	}

	/**
	 * 属性ddisabledate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDdisabledate
	 *            UFDate
	 */
	public void setDdisabledate(UFDate newDdisabledate) {

		ddisabledate = newDdisabledate;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性brate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDouble
	 */
	public UFDouble getBrate() {
		return brate;
	}

	/**
	 * 属性brate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newBrate
	 *            UFDouble
	 */
	public void setBrate(UFDouble newBrate) {

		brate = newBrate;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性dtransactdate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDate
	 */
	public UFDate getDtransactdate() {
		return dtransactdate;
	}

	/**
	 * 属性dtransactdate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDtransactdate
	 *            UFDate
	 */
	public void setDtransactdate(UFDate newDtransactdate) {

		dtransactdate = newDtransactdate;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性pk_source的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getPk_source() {
		return pk_source;
	}

	/**
	 * 属性pk_source的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newPk_source
	 *            String
	 */
	public void setPk_source(String newPk_source) {

		pk_source = newPk_source;
	}

	/**
	 * 属性pk_org的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newPk_org
	 *            String
	 */
	public void setPk_org(String newPk_org) {

		pk_org = newPk_org;
	}

	/**
	 * 属性frate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFrate() {
		return frate;
	}

	/**
	 * 属性frate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newFrate
	 *            UFDouble
	 */
	public void setFrate(UFDouble newFrate) {

		frate = newFrate;
	}

	/**
	 * 属性vdisablemanid的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getVdisablemanid() {
		return vdisablemanid;
	}

	/**
	 * 属性vdisablemanid的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newVdisablemanid
	 *            String
	 */
	public void setVdisablemanid(String newVdisablemanid) {

		vdisablemanid = newVdisablemanid;
	}

	/**
	 * 属性moneyf的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyf() {
		return moneyf;
	}

	/**
	 * 属性moneyf的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newMoneyf
	 *            UFDouble
	 */
	public void setMoneyf(UFDouble newMoneyf) {

		moneyf = newMoneyf;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性vtransactorid的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getVtransactorid() {
		return vtransactorid;
	}

	/**
	 * 属性vtransactorid的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newVtransactorid
	 *            String
	 */
	public void setVtransactorid(String newVtransactorid) {

		vtransactorid = newVtransactorid;
	}

	/**
	 * 属性dcollectiondate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDate
	 */
	public UFDate getDcollectiondate() {
		return dcollectiondate;
	}

	/**
	 * 属性dcollectiondate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDcollectiondate
	 *            UFDate
	 */
	public void setDcollectiondate(UFDate newDcollectiondate) {

		dcollectiondate = newDcollectiondate;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性disablenote的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getDisablenote() {
		return disablenote;
	}

	/**
	 * 属性disablenote的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDisablenote
	 *            String
	 */
	public void setDisablenote(String newDisablenote) {

		disablenote = newDisablenote;
	}

	/**
	 * 属性note的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/**
	 * 属性note的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newNote
	 *            String
	 */
	public void setNote(String newNote) {

		note = newNote;
	}

	/**
	 * 属性pk_billtypecode的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newPk_billtypecode
	 *            String
	 */
	public void setPk_billtypecode(String newPk_billtypecode) {

		pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性pk_collection的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getPk_collection() {
		return pk_collection;
	}

	/**
	 * 属性pk_collection的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newPk_collection
	 *            String
	 */
	public void setPk_collection(String newPk_collection) {

		pk_collection = newPk_collection;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性moneyy的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyy() {
		return moneyy;
	}

	/**
	 * 属性moneyy的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newMoneyy
	 *            UFDouble
	 */
	public void setMoneyy(UFDouble newMoneyy) {

		moneyy = newMoneyy;
	}

	/**
	 * 属性dconsigndate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDate
	 */
	public UFDate getDconsigndate() {
		return dconsigndate;
	}

	/**
	 * 属性dconsigndate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDconsigndate
	 *            UFDate
	 */
	public void setDconsigndate(UFDate newDconsigndate) {

		dconsigndate = newDconsigndate;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性moneyb的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyb() {
		return moneyb;
	}

	/**
	 * 属性moneyb的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newMoneyb
	 *            UFDouble
	 */
	public void setMoneyb(UFDouble newMoneyb) {

		moneyb = newMoneyb;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性doperatedate的Getter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return UFDate
	 */
	public UFDate getDoperatedate() {
		return doperatedate;
	}

	/**
	 * 属性doperatedate的Setter方法.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @param newDoperatedate
	 *            UFDate
	 */
	public void setDoperatedate(UFDate newDoperatedate) {

		doperatedate = newDoperatedate;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("36201020", "UPP36201020-000013")/*
																											 * @res
																											 * "下列字段不能为空:"
																											 */);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-8-22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-8-22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_collection";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-8-22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_collection";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2007-8-22
	 */
	public CollectionVO() {

		super();
	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2007-8-22
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_collection";

	}

	public String getFkdw() {
		return fkdw;
	}

	public void setFkdw(String fkdw) {
		this.fkdw = fkdw;
	}

	public String getFkkhh() {
		return fkkhh;
	}

	public void setFkkhh(String fkkhh) {
		this.fkkhh = fkkhh;
	}

	public String getFkdwyhzh() {
		return fkdwyhzh;
	}

	public void setFkdwyhzh(String fkdwyhzh) {
		this.fkdwyhzh = fkdwyhzh;
	}

	public String getCprmc() {
		return cprmc;
	}

	public void setCprmc(String cprmc) {
		this.cprmc = cprmc;
	}

	public String getYbbz() {
		return ybbz;
	}

	public void setYbbz(String ybbz) {
		this.ybbz = ybbz;
	}

	public UFDouble getPmje() {
		return pmje;
	}

	public void setPmje(UFDouble pmje) {
		this.pmje = pmje;
	}

	public UFDate getCprq() {
		return cprq;
	}

	public void setCprq(UFDate cprq) {
		this.cprq = cprq;
	}

	public UFDate getDqrq() {
		return dqrq;
	}

	public void setDqrq(UFDate dqrq) {
		this.dqrq = dqrq;
	}

	public String getPjlx() {
		return pjlx;
	}

	public void setPjlx(String pjlx) {
		this.pjlx = pjlx;
	}

	public void setAttributeValue(String attributeName, Object value) {
		if (attributeName.equals(VBILLSTATUS)) {
			if (value != null)
				setVbillstatus(new Integer(value.toString()));
		} else if (attributeName.equals(DCONSIGNDATE)) {
			if (value != null)
				setDconsigndate(new UFDate(value.toString()));
		} else if (attributeName.equals(DCOLLECTIONDATE)) {
			if (value != null)
				setDcollectiondate(new UFDate(value.toString()));
		} else if (attributeName.equals(CPRQ)) {
			if (value != null)
				setCprq(new UFDate(value.toString()));
		} else if (attributeName.equals(DQRQ)) {
			if (value != null)
				setDqrq(new UFDate(value.toString()));
		} else if (attributeName.equals(SPRQ)) {
			if (value != null)
				setSprq(new UFDate(value.toString()));
		} else {
			super.setAttributeValue(attributeName, value);
		}
	}

	public String getVvoucherid() {
		return vvoucherid;
	}

	public void setVvoucherid(String vvoucherid) {
		this.vvoucherid = vvoucherid;
	}

	public UFDate getDvoucherdate() {
		return dvoucherdate;
	}

	public void setDvoucherdate(UFDate dvoucherdate) {
		this.dvoucherdate = dvoucherdate;
	}

	public String getHolderacc() {
		return holderacc;
	}

	public void setHolderacc(String holderacc) {
		this.holderacc = holderacc;
	}

	public String getPk_holderbank() {
		return pk_holderbank;
	}

	public void setPk_holderbank(String pk_holderbank) {
		this.pk_holderbank = pk_holderbank;
	}

	public String getPk_baseinfo() {
		return pk_baseinfo;
	}

	public void setPk_baseinfo(String pk_baseinfo) {
		this.pk_baseinfo = pk_baseinfo;
	}

	public String getOpbilltype() {
		return opbilltype;
	}

	public void setOpbilltype(String opbilltype) {
		this.opbilltype = opbilltype;
	}

	public String getCollectionno() {
		return collectionno;
	}

	public void setCollectionno(String collectionno) {
		this.collectionno = collectionno;
	}

	public String getReceiveunit() {
		return receiveunit;
	}

	public void setReceiveunit(String receiveunit) {
		this.receiveunit = receiveunit;
	}

	public String getReceivebankacc() {
		return receivebankacc;
	}

	public void setReceivebankacc(String receivebankacc) {
		this.receivebankacc = receivebankacc;
	}

	public String getFbmbillno() {
		return fbmbillno;
	}

	public void setFbmbillno(String fbmbillno) {
		this.fbmbillno = fbmbillno;
	}

	public UFBoolean getUnitvoucher() {
		return unitvoucher;
	}

	public void setUnitvoucher(UFBoolean unitvoucher) {
		this.unitvoucher = unitvoucher;
	}

	public String getCollectionitem() {
		return collectionitem;
	}

	public void setCollectionitem(String collectionitem) {
		this.collectionitem = collectionitem;
	}

	public String getCollectionplanitem() {
		return collectionplanitem;
	}

	public void setCollectionplanitem(String collectionplanitem) {
		this.collectionplanitem = collectionplanitem;
	}

	public String getFbmplanitem() {
		return fbmplanitem;
	}

	public void setFbmplanitem(String fbmplanitem) {
		this.fbmplanitem = fbmplanitem;
	}

	public String getFbmitem() {
		return fbmitem;
	}

	public void setFbmitem(String fbmitem) {
		this.fbmitem = fbmitem;
	}

	public UFBoolean getWritebankacc() {
		return writebankacc;
	}

	public void setWritebankacc(UFBoolean writebankacc) {
		this.writebankacc = writebankacc;
	}

	public UFBoolean getWriteinneracc() {
		return writeinneracc;
	}

	public void setWriteinneracc(UFBoolean writeinneracc) {
		this.writeinneracc = writeinneracc;
	}
	
	public UFBoolean getWriteplan() {
		return writeplan;
	}

	public void setWriteplan(UFBoolean writeplan) {
		this.writeplan = writeplan;
	}
}