/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fbm.acceptbill;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2007-9-3
 * 
 * @author author
 * @version Your Project 1.0
 */
public class AcceptVO extends SuperVO {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	public static String tablecode = "fbm_accept";
	public static String BASEINFO_TAB = "fbm_baseinfo";

	public String def5;
	public String pk_corp;
	public UFDate dacceptdate;
	public Integer dr;
	public String voperatorid;
	public String vapprovenote;
	public UFDouble brate;
	public Integer vbillstatus;
	public String pk_source;
	public String pk_org;
	public UFDouble frate;
	public UFDateTime ts;
	public UFDouble moneyf;
	public String vbillno;
	public String pk_accept;
	public String pk_baseinfo;
	public String def1;
	public String backsecaccount;
	public String note;
	public String pk_billtypecode;
	public UFDate dapprovedate;
	public String vapproveid;
	public String def2;
	public UFDouble moneyy;
	public String def4;
	public UFDouble moneyb;
	public UFDate dacceptnotedate;
	public String def3;
	public UFDate doperatedate;
	public UFDouble backsecmoney;
	public String cctype;
	public String acceptno;
	public String pk_loanbank;
	public String holdunit;
	public String holderacc;
	public String holderbank;
	public String holderaccname;
	public String holderaccode;
	public String holdunitname;
	public String vvouchermanid;
	public UFDate vvoucherdate;
	public UFBoolean unitvoucher;
	public String acceptitem;// 承兑付款支出项目
	public String acceptplanitem;// 承兑付款支出计划项目

	// 从开票中携带的字段
	public UFDouble securityrate;
	public UFDouble securitymoney;

	public UFDouble securitymoneyb; // 保证金本币
	public UFDouble securitymoneyf; // 保证金辅币

	private UFDouble backsecmoneyb; // 返回保证金本币金额

	private UFDouble backsecmoneyf; // 返回保证金辅币金额

	public String securityaccount;
	public String impawnmode;

	public String paybankname;
	public String receivebankname;
	public String paybank;
	public String receivebank;

	// baseinfo
	// 到期日期
	public UFDate enddate;

	// 承兑协议编号
	public String acceptanceno;

	// 付款单位
	public String payunit;

	// 收票日期
	public UFDate receivedate;

	// 收款单位
	public String receiveunit;

	// 出票日期
	public UFDate invoicedate;

	// 出票人全称
	public String invoiceunit;

	// 票据类型
	public String fbmbilltype;

	// 交易合同编号
	public String contractno;

	// 收款单位银行账号
	public String receivebankacc;

	// 币种
	public String pk_curr;
	// 票面金额
	public UFDouble billmoneyy;
	// 票据状态
	public String fbillstatus;

	public String fbmbillno;

	/**
	 * 临时变量，保存是否要回写计划,true：回写；null || false：不回写
	 */
	private UFBoolean writePlan;

	private UFBoolean writebankacc;

	private UFBoolean writeinneracc;

	public static final String DEF5 = "def5";
	public static final String PAYBANKACC = "paybankacc";
	public static final String PK_CORP = "pk_corp";
	public static final String DACCEPTDATE = "dacceptdate";
	public static final String DR = "dr";
	public static final String VOPERATORID = "voperatorid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String BRATE = "brate";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String PK_SOURCE = "pk_source";
	public static final String PK_ORG = "pk_org";
	public static final String FRATE = "frate";
	public static final String TS = "ts";
	public static final String MONEYF = "moneyf";
	public static final String VBILLNO = "vbillno";
	public static final String PK_ACCEPT = "pk_accept";
	public static final String PK_BASEINFO = "pk_baseinfo";
	public static final String DEF1 = "def1";
	public static final String BACKSECACCOUNT = "backsecaccount";
	public static final String NOTE = "note";
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DEF2 = "def2";
	public static final String MONEYY = "moneyy";
	public static final String DEF4 = "def4";
	public static final String MONEYB = "moneyb";
	public static final String DACCEPTNOTEDATE = "dacceptnotedate";
	public static final String DEF3 = "def3";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String BACKSECMONEY = "backsecmoney";
	public static final String ACCEPTNO = "acceptno";

	public static final String FBMBILLTYPE = "fbmbilltype";

	public static final String ENDDATE = "enddate";

	public static final String ACCEPTANCENO = "acceptanceno";

	public static final String PAYUNIT = "payunit";

	public static final String RECEIVEDATE = "receivedate";

	public static final String RECEIVEUNIT = "receiveunit";

	public static final String INVOICEDATE = "invoicedate";

	public static final String INVOICEUNIT = "invoiceunit";

	public static final String CONTRACTNO = "contractno";

	public static final String RECEIVEBANKACC = "receivebankacc";

	public static final String PK_CURR = "pk_curr";

	public static final String SECURITYRATE = "securityrate";

	public static final String SECURITYMONEY = "securitymoney";

	public static final String SECURITYACCOUNT = "securityaccount";

	public static final String IMPAWNMODE = "impawnmode";

	public static final String BILLMONEYY = "billmoneyy";

	public static final String PAYBANKNAME = "paybankname";

	public static final String RECEIVEBANKNAME = "receivebankname";

	public static final String FBILLSTATUS = "fbillstatus";

	public static final String CCTYPE = "cctype";

	public static final String PK_LOANBANK = "pk_loanbank";

	public static final String HOLDUNIT = "holdunit";

	public static final String HOLDERACC = "holderacc";

	public static final String HOLDERBANK = "holderbank";

	public static final String HOLDERACCNAME = "holderaccname";

	public static final String HOLDERACCODE = "holderaccode";

	public static final String HOLDUNITNAME = "holdunitname";

	public static final String VVOUCHERDATE = "vvoucherdate";

	public static final String VVOUCHERMANID = "vvouchermanid";

	public static final String UNITVOUCHER = "unitvoucher";

	public static final String ACCEPTPLANITEM = "acceptplanitem";

	public static final String FBMBILLNO = "fbmbillno";

	public static final String SECURITYMONEYB = "securitymoneyb";

	public static final String SECURITYMONEYF = "securitymoneyf";

	public static final String BACKSECMONEYB = "backsecmoneyb";

	public static final String BACKSECMONEYF = "backsecmoneyf";
	
	public static final String PAYBANK = "paybank";
	
	public static final String RECEIVEBANK = "receivebank";

	public String getAcceptno() {
		return acceptno;
	}

	public void setAcceptno(String acceptno) {
		this.acceptno = acceptno;
	}

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性dacceptdate的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDate
	 */
	public UFDate getDacceptdate() {
		return dacceptdate;
	}

	/**
	 * 属性dacceptdate的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDacceptdate
	 *            UFDate
	 */
	public void setDacceptdate(UFDate newDacceptdate) {

		dacceptdate = newDacceptdate;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDouble
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDr
	 *            UFDouble
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性brate的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDouble
	 */
	public UFDouble getBrate() {
		return brate;
	}

	/**
	 * 属性brate的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newBrate
	 *            UFDouble
	 */
	public void setBrate(UFDouble newBrate) {

		brate = newBrate;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性pk_source的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getPk_source() {
		return pk_source;
	}

	/**
	 * 属性pk_source的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_source
	 *            String
	 */
	public void setPk_source(String newPk_source) {

		pk_source = newPk_source;
	}

	/**
	 * 属性pk_org的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_org
	 *            String
	 */
	public void setPk_org(String newPk_org) {

		pk_org = newPk_org;
	}

	/**
	 * 属性frate的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFrate() {
		return frate;
	}

	/**
	 * 属性frate的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newFrate
	 *            UFDouble
	 */
	public void setFrate(UFDouble newFrate) {

		frate = newFrate;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {

		ts = newTs;
	}

	/**
	 * 属性moneyf的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyf() {
		return moneyf;
	}

	/**
	 * 属性moneyf的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newMoneyf
	 *            UFDouble
	 */
	public void setMoneyf(UFDouble newMoneyf) {

		moneyf = newMoneyf;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性pk_accept的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getPk_accept() {
		return pk_accept;
	}

	/**
	 * 属性pk_accept的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_accept
	 *            String
	 */
	public void setPk_accept(String newPk_accept) {

		pk_accept = newPk_accept;
	}

	/**
	 * 属性pk_baseinfo的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getPk_baseinfo() {
		return pk_baseinfo;
	}

	/**
	 * 属性pk_baseinfo的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_baseinfo
	 *            String
	 */
	public void setPk_baseinfo(String newPk_baseinfo) {

		pk_baseinfo = newPk_baseinfo;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性backsecaccount的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getBacksecaccount() {
		return backsecaccount;
	}

	/**
	 * 属性backsecaccount的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newBacksecaccount
	 *            String
	 */
	public void setBacksecaccount(String newBacksecaccount) {

		backsecaccount = newBacksecaccount;
	}

	/**
	 * 属性note的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/**
	 * 属性note的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newNote
	 *            String
	 */
	public void setNote(String newNote) {

		note = newNote;
	}

	/**
	 * 属性pk_billtypecode的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_billtypecode
	 *            String
	 */
	public void setPk_billtypecode(String newPk_billtypecode) {

		pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性moneyy的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyy() {
		return moneyy;
	}

	/**
	 * 属性moneyy的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newMoneyy
	 *            UFDouble
	 */
	public void setMoneyy(UFDouble newMoneyy) {

		moneyy = newMoneyy;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性moneyb的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyb() {
		return moneyb;
	}

	/**
	 * 属性moneyb的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newMoneyb
	 *            UFDouble
	 */
	public void setMoneyb(UFDouble newMoneyb) {

		moneyb = newMoneyb;
	}

	/**
	 * 属性dacceptnotedate的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDate
	 */
	public UFDate getDacceptnotedate() {
		return dacceptnotedate;
	}

	/**
	 * 属性dacceptnotedate的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDacceptnotedate
	 *            UFDate
	 */
	public void setDacceptnotedate(UFDate newDacceptnotedate) {

		dacceptnotedate = newDacceptnotedate;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性doperatedate的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDate
	 */
	public UFDate getDoperatedate() {
		return doperatedate;
	}

	/**
	 * 属性doperatedate的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newDoperatedate
	 *            UFDate
	 */
	public void setDoperatedate(UFDate newDoperatedate) {

		doperatedate = newDoperatedate;
	}

	/**
	 * 属性backsecmoney的Getter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return UFDouble
	 */
	public UFDouble getBacksecmoney() {
		return backsecmoney;
	}

	/**
	 * 属性backsecmoney的Setter方法.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newBacksecmoney
	 *            UFDouble
	 */
	public void setBacksecmoney(UFDouble newBacksecmoney) {

		backsecmoney = newBacksecmoney;
	}

	public UFDate getEnddate() {
		return enddate;
	}

	public void setEnddate(UFDate enddate) {
		this.enddate = enddate;
	}

	public String getAcceptanceno() {
		return acceptanceno;
	}

	public void setAcceptanceno(String acceptanceno) {
		this.acceptanceno = acceptanceno;
	}

	public String getPayunit() {
		return payunit;
	}

	public void setPayunit(String payunit) {
		this.payunit = payunit;
	}

	public UFDate getReceivedate() {
		return receivedate;
	}

	public void setReceivedate(UFDate receivedate) {
		this.receivedate = receivedate;
	}

	public String getReceiveunit() {
		return receiveunit;
	}

	public void setReceiveunit(String receiveunit) {
		this.receiveunit = receiveunit;
	}

	public UFDate getInvoicedate() {
		return invoicedate;
	}

	public void setInvoicedate(UFDate invoicedate) {
		this.invoicedate = invoicedate;
	}

	public String getInvoiceunit() {
		return invoiceunit;
	}

	public void setInvoiceunit(String invoiceunit) {
		this.invoiceunit = invoiceunit;
	}

	public String getFbmbilltype() {
		return fbmbilltype;
	}

	public void setFbmbilltype(String fbmbilltype) {
		this.fbmbilltype = fbmbilltype;
	}

	public String getContractno() {
		return contractno;
	}

	public void setContractno(String contractno) {
		this.contractno = contractno;
	}

	public String getReceivebankacc() {
		return receivebankacc;
	}

	public void setReceivebankacc(String receivebankacc) {
		this.receivebankacc = receivebankacc;
	}

	public String getPk_curr() {
		return pk_curr;
	}

	public void setPk_curr(String pk_curr) {
		this.pk_curr = pk_curr;
	}

	public UFDouble getSecurityrate() {
		return securityrate;
	}

	public void setSecurityrate(UFDouble securityrate) {
		this.securityrate = securityrate;
	}

	public UFDouble getSecuritymoney() {
		return securitymoney;
	}

	public void setSecuritymoney(UFDouble securitymoney) {
		this.securitymoney = securitymoney;
	}

	public String getSecurityaccount() {
		return securityaccount;
	}

	public void setSecurityaccount(String securityaccount) {
		this.securityaccount = securityaccount;
	}

	public String getImpawnmode() {
		return impawnmode;
	}

	public void setImpawnmode(String impawnmode) {
		this.impawnmode = impawnmode;
	}

	public UFDouble getBillmoneyy() {
		return billmoneyy;
	}

	public void setBillmoneyy(UFDouble billmoneyy) {
		this.billmoneyy = billmoneyy;
	}

	public String getPaybankname() {
		return paybankname;
	}

	public void setPaybankname(String paybankname) {
		this.paybankname = paybankname;
	}

	public String getReceivebankname() {
		return receivebankname;
	}

	public void setReceivebankname(String receivebankname) {
		this.receivebankname = receivebankname;
	}

	public String getFbillstatus() {
		return fbillstatus;
	}

	public void setFbillstatus(String fbillstatus) {
		this.fbillstatus = fbillstatus;
	}

	public String getCctype() {
		return cctype;
	}

	public void setCctype(String cctype) {
		this.cctype = cctype;
	}

	public String getPk_loanbank() {
		return pk_loanbank;
	}

	public void setPk_loanbank(String pk_loanbank) {
		this.pk_loanbank = pk_loanbank;
	}

	public String getHoldunit() {
		return holdunit;
	}

	public void setHoldunit(String holdunit) {
		this.holdunit = holdunit;
	}

	public String getHolderacc() {
		return holderacc;
	}

	public void setHolderacc(String holderacc) {
		this.holderacc = holderacc;
	}

	public String getHolderbank() {
		return holderbank;
	}

	public void setHolderbank(String holderbank) {
		this.holderbank = holderbank;
	}

	public String getHolderaccname() {
		return holderaccname;
	}

	public void setHolderaccname(String holderaccname) {
		this.holderaccname = holderaccname;
	}

	public String getHolderaccode() {
		return holderaccode;
	}

	public void setHolderaccode(String holderaccode) {
		this.holderaccode = holderaccode;
	}

	public String getHoldunitname() {
		return holdunitname;
	}

	public void setHoldunitname(String holdunitname) {
		this.holdunitname = holdunitname;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_accept == null) {
			errFields.add(new String("pk_accept"));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("36201510", "UPP36201510-000006")/*
																											 * @res
																											 * "下列字段不能为空:"
																											 */);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-9-3
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-9-3
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_accept";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-9-3
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_accept";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2007-9-3
	 */
	public AcceptVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_accept
	 *            主键值
	 */
	public AcceptVO(String newPk_accept) {

		// 为主键字段赋值:
		pk_accept = newPk_accept;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_accept;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @param newPk_accept
	 *            String
	 */
	public void setPrimaryKey(String newPk_accept) {

		pk_accept = newPk_accept;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2007-9-3
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_accept";

	}

	public String getVvouchermanid() {
		return vvouchermanid;
	}

	public void setVvouchermanid(String vvouchermanid) {
		this.vvouchermanid = vvouchermanid;
	}

	public UFDate getVvoucherdate() {
		return vvoucherdate;
	}

	public void setVvoucherdate(UFDate vvoucherdate) {
		this.vvoucherdate = vvoucherdate;
	}

	public UFBoolean getUnitvoucher() {
		return unitvoucher;
	}

	public void setUnitvoucher(UFBoolean unitvoucher) {
		this.unitvoucher = unitvoucher;
	}

	public String getAcceptitem() {
		return acceptitem;
	}

	public void setAcceptitem(String acceptitem) {
		this.acceptitem = acceptitem;
	}

	public String getAcceptplanitem() {
		return acceptplanitem;
	}

	public void setAcceptplanitem(String acceptplanitem) {
		this.acceptplanitem = acceptplanitem;
	}

	public UFBoolean getWritePlan() {
		return writePlan;
	}

	public void setWritePlan(UFBoolean writePlan) {
		this.writePlan = writePlan;
	}

	public String getFbmbillno() {
		return fbmbillno;
	}

	public void setFbmbillno(String fbmbillno) {
		this.fbmbillno = fbmbillno;
	}

	public UFDouble getSecuritymoneyb() {
		return securitymoneyb;
	}

	public void setSecuritymoneyb(UFDouble securitymoneyb) {
		this.securitymoneyb = securitymoneyb;
	}

	public UFDouble getSecuritymoneyf() {
		return securitymoneyf;
	}

	public void setSecuritymoneyf(UFDouble securitymoneyf) {
		this.securitymoneyf = securitymoneyf;
	}

	public void setBacksecmoneyb(UFDouble backsecmoneyb) {
		this.backsecmoneyb = backsecmoneyb;
	}

	public UFDouble getBacksecmoneyf() {
		return backsecmoneyf;
	}

	public UFDouble getBacksecmoneyb() {
		return backsecmoneyb;
	}

	public void setBacksecmoneyf(UFDouble backsecmoneyf) {
		this.backsecmoneyf = backsecmoneyf;
	}

	public UFBoolean getWritebankacc() {
		return writebankacc;
	}

	public void setWritebankacc(UFBoolean writebankacc) {
		this.writebankacc = writebankacc;
	}

	public UFBoolean getWriteinneracc() {
		return writeinneracc;
	}

	public void setWriteinneracc(UFBoolean writeinneracc) {
		this.writeinneracc = writeinneracc;
	}

	public String getPaybank() {
		return paybank;
	}

	public void setPaybank(String paybank) {
		this.paybank = paybank;
	}

	public String getReceivebank() {
		return receivebank;
	}

	public void setReceivebank(String receivebank) {
		this.receivebank = receivebank;
	}

	
}