  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.fbm.impawn;

	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2007-9-19
 * @author author
 * @version Your Project 1.0
 */
     public class ImpawnVO extends SuperVO {

             public String def5;
             public String pk_corp;
             public UFDate impawndate;
             public String impawnbackunit;
             public String creditunit;
             public UFDouble impawnrate;
             public String voperatorid;
             public String vapprovenote;
             public UFDouble brate;
             public String pk_impawn;
             public Integer vbillstatus;
             public String pk_source;
             public String pk_org;
             public UFDouble frate;
             public UFDouble moneyf;
             public String vbillno;
             public String debitunit;
             public UFDouble impawnable;
             public String pk_baseinfo;
             public String def1;
             public String impawnbank;
             public UFDouble evaluatevalue;
             public String impawnunit;
             public String pk_billtypecode;
             public UFDate dapprovedate;
             public UFDate impawnbackdate;
             public String vapproveid;
             public String def2;
             public UFDouble moneyy;
             public String def4;
             public UFDouble moneyb;
             public String evaluateunit;
             public String def3;
             public UFDate doperatedate;

             public String ts;
             public UFDate impawnenddate;//质押到期日期

             //增加一批自定义项
             public String fbmbillno;//票据编号
             public String fbmbilltype;//票据类型
             public UFDate gatherdate;//收到日期
             public UFDate invoicedate;//出票日期
             public UFDate enddate;//到期日期
             public String holdunit;//持票人名称
             //public String ownBankNo;//持票人银行账号
            // public String ownBankName;//持票人开户行
             public String payunit;//付款人名称
             public String paybankacc;//付款人银行账号
             public String paybank;//付款人开户行
             public String pk_curr;//币种
             public String invoiceunit;//出票单位名称

             public static final String  DEF5="def5";
             public static final String  PK_CORP="pk_corp";
             public static final String  IMPAWNDATE="impawndate";
             public static final String  IMPAWNBACKUNIT="impawnbackunit";
             public static final String  CREDITUNIT="creditunit";
             public static final String  IMPAWNRATE="impawnrate";
             public static final String  VOPERATORID="voperatorid";
             public static final String  VAPPROVENOTE="vapprovenote";
             public static final String  BRATE="brate";
             public static final String  PK_IMPAWN="pk_impawn";
             public static final String  VBILLSTATUS="vbillstatus";
             public static final String  PK_SOURCE="pk_source";
             public static final String  PK_ORG="pk_org";
             public static final String  FRATE="frate";
             public static final String  MONEYF="moneyf";
             public static final String  VBILLNO="vbillno";
             public static final String  DEBITUNIT="debitunit";
             public static final String  IMPAWNABLE="impawnable";
             public static final String  PK_BASEINFO="pk_baseinfo";
             public static final String  DEF1="def1";
             public static final String  IMPAWNBANK="impawnbank";
             public static final String  EVALUATEVALUE="evaluatevalue";
             public static final String  IMPAWNUNIT="impawnunit";
             public static final String  PK_BILLTYPECODE="pk_billtypecode";
             public static final String  DAPPROVEDATE="dapprovedate";
             public static final String  IMPAWNBACKDATE="impawnbackdate";
             public static final String  VAPPROVEID="vapproveid";
             public static final String  DEF2="def2";
             public static final String  MONEYY="moneyy";
             public static final String  DEF4="def4";
             public static final String  MONEYB="moneyb";
             public static final String  EVALUATEUNIT="evaluateunit";
             public static final String  DEF3="def3";
             public static final String  DOPERATEDATE="doperatedate";

             public static final String TS = "ts";

             //自定义项目
             public static final String FBMBILLNO = "fbmbillno";//票据编号
             public static final String FBMBILLTYPE = "fbmbilltype";//票据类型
             public static final String GATHERDATE = "gatherdate";//收到日期
             public static final String INVOICEDATE = "invoicedate";//出票日期
             public static final String ENDDATE = "enddate";//到期日期
             public static final String HOLDUNIT = "holdunit";//持票人名称
             public static final String PAYUNIT = "payunit";//付款人名称
             public static final String PAYBANKACC = "paybankacc";//付款人银行账号
             public static final String PAYBANK = "paybank";//付款人开户行
             public static final String PK_CURR = "pk_curr";//币种
             public static final String INVOICEUNIT = "invoiceunit";//出票单位名称
             public static final String IMPAWNENDDATE = "impawnenddate";//质押到期日期

              

		/**
			 * @return the ts
			 */
			public String getTs() {
				return ts;
			}

			/**
			 * @param ts the ts to set
			 */
			public void setTs(String ts) {
				this.ts = ts;
			}

		/**
			 * @return the invoiceunit
			 */
			public String getInvoiceunit() {
				return invoiceunit;
			}

			/**
			 * @param invoiceunit the invoiceunit to set
			 */
			public void setInvoiceunit(String invoiceunit) {
				this.invoiceunit = invoiceunit;
			}

		public String getFbmbillno() {
				return fbmbillno;
			}

			public void setFbmbillno(String fbmbillno) {
				this.fbmbillno = fbmbillno;
			}

		public String getFbmbilltype() {
				return fbmbilltype;
			}

			public void setFbmbilltype(String fbmbilltype) {
				this.fbmbilltype = fbmbilltype;
			}

			public UFDate getGatherdate() {
				return gatherdate;
			}

			public void setGatherdate(UFDate gatherdate) {
				this.gatherdate = gatherdate;
			}

			public UFDate getInvoicedate() {
				return invoicedate;
			}

			public void setInvoicedate(UFDate invoicedate) {
				this.invoicedate = invoicedate;
			}

			public UFDate getEnddate() {
				return enddate;
			}

			public void setEnddate(UFDate enddate) {
				this.enddate = enddate;
			}

			public String getHoldunit() {
				return holdunit;
			}

			public void setHoldunit(String holdunit) {
				this.holdunit = holdunit;
			}

			public String getPayunit() {
				return payunit;
			}

			public void setPayunit(String payunit) {
				this.payunit = payunit;
			}

			public String getPaybankacc() {
				return paybankacc;
			}

			public void setPaybankacc(String paybankacc) {
				this.paybankacc = paybankacc;
			}

			public String getPaybank() {
				return paybank;
			}

			public void setPaybank(String paybank) {
				this.paybank = paybank;
			}

			public String getPk_curr() {
				return pk_curr;
			}

			public void setPk_curr(String pk_curr) {
				this.pk_curr = pk_curr;
			}

		/**
	   * 属性def5的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getDef5() {
		 return def5;
	  }

     /**
	   * 属性def5的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDef5 String
	   */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	 }

        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }

     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	 }

        /**
	   * 属性impawndate的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDate
	   */
	 public UFDate getImpawndate() {
		 return impawndate;
	  }

     /**
	   * 属性impawndate的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newImpawndate UFDate
	   */
	public void setImpawndate(UFDate newImpawndate) {

		impawndate = newImpawndate;
	 }

        /**
	   * 属性impawnbackunit的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getImpawnbackunit() {
		 return impawnbackunit;
	  }

     /**
	   * 属性impawnbackunit的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newImpawnbackunit String
	   */
	public void setImpawnbackunit(String newImpawnbackunit) {

		impawnbackunit = newImpawnbackunit;
	 }

        /**
	   * 属性creditunit的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getCreditunit() {
		 return creditunit;
	  }

     /**
	   * 属性creditunit的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newCreditunit String
	   */
	public void setCreditunit(String newCreditunit) {

		creditunit = newCreditunit;
	 }

        /**
	   * 属性impawnrate的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getImpawnrate() {
		 return impawnrate;
	  }

     /**
	   * 属性impawnrate的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newImpawnrate UFDouble
	   */
	public void setImpawnrate(UFDouble newImpawnrate) {

		impawnrate = newImpawnrate;
	 }

        /**
	   * 属性voperatorid的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getVoperatorid() {
		 return voperatorid;
	  }

     /**
	   * 属性voperatorid的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newVoperatorid String
	   */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	 }

        /**
	   * 属性vapprovenote的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getVapprovenote() {
		 return vapprovenote;
	  }

     /**
	   * 属性vapprovenote的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newVapprovenote String
	   */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	 }

        /**
	   * 属性brate的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getBrate() {
		 return brate;
	  }

     /**
	   * 属性brate的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newBrate UFDouble
	   */
	public void setBrate(UFDouble newBrate) {

		brate = newBrate;
	 }

        /**
	   * 属性pk_impawn的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getPk_impawn() {
		 return pk_impawn;
	  }

     /**
	   * 属性pk_impawn的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newPk_impawn String
	   */
	public void setPk_impawn(String newPk_impawn) {

		pk_impawn = newPk_impawn;
	 }

        /**
	   * 属性vbillstatus的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return Integer
	   */
	 public Integer getVbillstatus() {
		 return vbillstatus;
	  }

     /**
	   * 属性vbillstatus的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newVbillstatus Integer
	   */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	 }

        /**
	   * 属性pk_source的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getPk_source() {
		 return pk_source;
	  }

     /**
	   * 属性pk_source的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newPk_source String
	   */
	public void setPk_source(String newPk_source) {

		pk_source = newPk_source;
	 }

        /**
	   * 属性pk_org的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getPk_org() {
		 return pk_org;
	  }

     /**
	   * 属性pk_org的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newPk_org String
	   */
	public void setPk_org(String newPk_org) {

		pk_org = newPk_org;
	 }

        /**
	   * 属性frate的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getFrate() {
		 return frate;
	  }

     /**
	   * 属性frate的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newFrate UFDouble
	   */
	public void setFrate(UFDouble newFrate) {

		frate = newFrate;
	 }

        /**
	   * 属性moneyf的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getMoneyf() {
		 return moneyf;
	  }

     /**
	   * 属性moneyf的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newMoneyf UFDouble
	   */
	public void setMoneyf(UFDouble newMoneyf) {

		moneyf = newMoneyf;
	 }

        /**
	   * 属性vbillno的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getVbillno() {
		 return vbillno;
	  }

     /**
	   * 属性vbillno的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newVbillno String
	   */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	 }

        /**
	   * 属性debitunit的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getDebitunit() {
		 return debitunit;
	  }

     /**
	   * 属性debitunit的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDebitunit String
	   */
	public void setDebitunit(String newDebitunit) {

		debitunit = newDebitunit;
	 }

        /**
	   * 属性impawnable的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getImpawnable() {
		 return impawnable;
	  }

     /**
	   * 属性impawnable的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newImpawnable UFDouble
	   */
	public void setImpawnable(UFDouble newImpawnable) {

		impawnable = newImpawnable;
	 }

        /**
	   * 属性pk_baseinfo的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getPk_baseinfo() {
		 return pk_baseinfo;
	  }

     /**
	   * 属性pk_baseinfo的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newPk_baseinfo String
	   */
	public void setPk_baseinfo(String newPk_baseinfo) {

		pk_baseinfo = newPk_baseinfo;
	 }

        /**
	   * 属性def1的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getDef1() {
		 return def1;
	  }

     /**
	   * 属性def1的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDef1 String
	   */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	 }

        /**
	   * 属性impawnbank的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getImpawnbank() {
		 return impawnbank;
	  }

     /**
	   * 属性impawnbank的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newImpawnbank String
	   */
	public void setImpawnbank(String newImpawnbank) {

		impawnbank = newImpawnbank;
	 }

        /**
	   * 属性evaluatevalue的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getEvaluatevalue() {
		 return evaluatevalue;
	  }

     /**
	   * 属性evaluatevalue的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newEvaluatevalue UFDouble
	   */
	public void setEvaluatevalue(UFDouble newEvaluatevalue) {

		evaluatevalue = newEvaluatevalue;
	 }

        /**
	   * 属性impawnunit的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getImpawnunit() {
		 return impawnunit;
	  }

     /**
	   * 属性impawnunit的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newImpawnunit String
	   */
	public void setImpawnunit(String newImpawnunit) {

		impawnunit = newImpawnunit;
	 }

        /**
	   * 属性pk_billtypecode的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getPk_billtypecode() {
		 return pk_billtypecode;
	  }

     /**
	   * 属性pk_billtypecode的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newPk_billtypecode String
	   */
	public void setPk_billtypecode(String newPk_billtypecode) {

		pk_billtypecode = newPk_billtypecode;
	 }

        /**
	   * 属性dapprovedate的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDate
	   */
	 public UFDate getDapprovedate() {
		 return dapprovedate;
	  }

     /**
	   * 属性dapprovedate的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDapprovedate UFDate
	   */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	 }

        /**
	   * 属性impawnbackdate的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDate
	   */
	 public UFDate getImpawnbackdate() {
		 return impawnbackdate;
	  }

     /**
	   * 属性impawnbackdate的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newImpawnbackdate UFDate
	   */
	public void setImpawnbackdate(UFDate newImpawnbackdate) {

		impawnbackdate = newImpawnbackdate;
	 }

        /**
	   * 属性vapproveid的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getVapproveid() {
		 return vapproveid;
	  }

     /**
	   * 属性vapproveid的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newVapproveid String
	   */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	 }

        /**
	   * 属性def2的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getDef2() {
		 return def2;
	  }

     /**
	   * 属性def2的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDef2 String
	   */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	 }

        /**
	   * 属性moneyy的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getMoneyy() {
		 return moneyy;
	  }

     /**
	   * 属性moneyy的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newMoneyy UFDouble
	   */
	public void setMoneyy(UFDouble newMoneyy) {

		moneyy = newMoneyy;
	 }

        /**
	   * 属性def4的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getDef4() {
		 return def4;
	  }

     /**
	   * 属性def4的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDef4 String
	   */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	 }

        /**
	   * 属性moneyb的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDouble
	   */
	 public UFDouble getMoneyb() {
		 return moneyb;
	  }

     /**
	   * 属性moneyb的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newMoneyb UFDouble
	   */
	public void setMoneyb(UFDouble newMoneyb) {

		moneyb = newMoneyb;
	 }

        /**
	   * 属性evaluateunit的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getEvaluateunit() {
		 return evaluateunit;
	  }

     /**
	   * 属性evaluateunit的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newEvaluateunit String
	   */
	public void setEvaluateunit(String newEvaluateunit) {

		evaluateunit = newEvaluateunit;
	 }

        /**
	   * 属性def3的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return String
	   */
	 public String getDef3() {
		 return def3;
	  }

     /**
	   * 属性def3的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDef3 String
	   */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	 }

        /**
	   * 属性doperatedate的Getter方法.
	   *
	   * 创建日期:2007-9-19
	   * @return UFDate
	   */
	 public UFDate getDoperatedate() {
		 return doperatedate;
	  }

     /**
	   * 属性doperatedate的Setter方法.
	   *
	   * 创建日期:2007-9-19
	   * @param newDoperatedate UFDate
	   */
	public void setDoperatedate(UFDate newDoperatedate) {

		doperatedate = newDoperatedate;
	 }


    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2007-9-19
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {

	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

	   		if (pk_impawn == null) {
			errFields.add(new String("pk_impawn"));
			  }

	    StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("36201040","UPP36201040-000019")/* @res"下列字段不能为空:"*/);
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }


   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2007-9-19
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {

	 	    return null;

	}

    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2007-9-19
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_impawn";
	 	}

	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2007-9-19
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_impawn";
	}

    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2007-9-19
	  */
	public ImpawnVO() {

			   super();
	  }

            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2007-9-19
	 * @param newPk_impawn 主键值
	 */
	 public ImpawnVO(String newPk_impawn) {

		// 为主键字段赋值:
		 pk_impawn = newPk_impawn;

    	}


	 
     public UFDate getImpawnenddate() {
				return impawnenddate;
			}

			public void setImpawnenddate(UFDate impawnenddate) {
				this.impawnenddate = impawnenddate;
			}

	/**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2007-9-19
	  * @return String
	  */
	   public String getPrimaryKey() {

		 return pk_impawn;

	   }

	   
     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2007-9-19
	  * @param newPk_impawn  String
	  */
	 public void setPrimaryKey(String newPk_impawn) {

				pk_impawn = newPk_impawn;

	 }

	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2007-9-19
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {

	   return "fbm_impawn";

	 }

}