/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fbm.returnbill;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 退票主表VO
 * </p>
 * 
 * 创建日期:2007-8-30
 * 
 * @author author
 * @version Your Project 1.0
 */
public class ReturnVO extends SuperVO {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	public String def5;
	public String pk_corp;
	public String vbillno;
	public String returnnote;
	public String returntype;
	public String returnperson;
	public Integer dr;
	public String def1;
	public String pk_return;
	public String voperatorid;
	public UFDate dreturndate;
	public String vapprovenote;
	public String pk_billtypecode;
	public UFDate busdate;
	public UFDate dapprovedate;
	public Integer vbillstatus;
	public String pk_org;
	public String vapproveid;
	public String def2;
	public UFDateTime ts;
	public String def4;
	public String def3;
	public UFDate doperatedate;
	public UFBoolean voucher;
	public UFDate dvoucherdate;
	public String vvoucherid;
	public UFBoolean unittally;
	public String unitplanitem;
	public String unititem;
	public UFBoolean writePlan;

	private UFBoolean writebankacc;

	private UFBoolean writeinneracc;

	public UFBoolean getWritebankacc() {
		return writebankacc;
	}

	public void setWritebankacc(UFBoolean writebankacc) {
		this.writebankacc = writebankacc;
	}

	public UFBoolean getWriteinneracc() {
		return writeinneracc;
	}

	public void setWriteinneracc(UFBoolean writeinneracc) {
		this.writeinneracc = writeinneracc;
	}

	public static final String DEF5 = "def5";
	public static final String PK_CORP = "pk_corp";
	public static final String VBILLNO = "vbillno";
	public static final String RETURNNOTE = "returnnote";
	public static final String RETURNTYPE = "returntype";
	public static final String RETURNPERSON = "returnperson";
	public static final String DR = "dr";
	public static final String DEF1 = "def1";
	public static final String PK_RETURN = "pk_return";
	public static final String VOPERATORID = "voperatorid";
	public static final String DRETURNDATE = "dreturndate";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	public static final String BUSDATE = "busdate";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String PK_ORG = "pk_org";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DEF2 = "def2";
	public static final String TS = "ts";
	public static final String DEF4 = "def4";
	public static final String DEF3 = "def3";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String VOUCHER = "voucher";
	public static final String UNITTALLY = "unittally";
	public static final String DVOUCHERDATE = "dvoucherdate";
	public static final String VVOUCHERID = "vvoucherid";
	public static final String UNITPLANITEM = "unitplanitem";
	public static final String UNITITEM = "unititem";

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性returnnote的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getReturnnote() {
		return returnnote;
	}

	/**
	 * 属性returnnote的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newReturnnote
	 *            String
	 */
	public void setReturnnote(String newReturnnote) {

		returnnote = newReturnnote;
	}

	/**
	 * 属性returntype的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getReturntype() {
		return returntype;
	}

	/**
	 * 属性returntype的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newReturntype
	 *            String
	 */
	public void setReturntype(String newReturntype) {

		returntype = newReturntype;
	}

	/**
	 * 属性returnperson的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getReturnperson() {
		return returnperson;
	}

	/**
	 * 属性returnperson的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newReturnperson
	 *            String
	 */
	public void setReturnperson(String newReturnperson) {

		returnperson = newReturnperson;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性pk_return的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getPk_return() {
		return pk_return;
	}

	/**
	 * 属性pk_return的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newPk_return
	 *            String
	 */
	public void setPk_return(String newPk_return) {

		pk_return = newPk_return;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性dreturndate的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return UFDate
	 */
	public UFDate getDreturndate() {
		return dreturndate;
	}

	/**
	 * 属性dreturndate的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDreturndate
	 *            UFDate
	 */
	public void setDreturndate(UFDate newDreturndate) {

		dreturndate = newDreturndate;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性pk_billtypecode的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newPk_billtypecode
	 *            String
	 */
	public void setPk_billtypecode(String newPk_billtypecode) {

		pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性busdate的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return UFDate
	 */
	public UFDate getBusdate() {
		return busdate;
	}

	/**
	 * 属性busdate的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newBusdate
	 *            UFDate
	 */
	public void setBusdate(UFDate newBusdate) {

		busdate = newBusdate;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性pk_org的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newPk_org
	 *            String
	 */
	public void setPk_org(String newPk_org) {

		pk_org = newPk_org;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {

		ts = newTs;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性doperatedate的Getter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return UFDate
	 */
	public UFDate getDoperatedate() {
		return doperatedate;
	}

	/**
	 * 属性doperatedate的Setter方法.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newDoperatedate
	 *            UFDate
	 */
	public void setDoperatedate(UFDate newDoperatedate) {

		doperatedate = newDoperatedate;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_return == null) {
			errFields.add(new String("pk_return"));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("362025", "UPP362025-000001")/*
																										 * @res
																										 * "下列字段不能为空:"
																										 */);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-8-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-8-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_return";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-8-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_return";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2007-8-30
	 */
	public ReturnVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newPk_return
	 *            主键值
	 */
	public ReturnVO(String newPk_return) {

		// 为主键字段赋值:
		pk_return = newPk_return;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_return;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @param newPk_return
	 *            String
	 */
	public void setPrimaryKey(String newPk_return) {

		pk_return = newPk_return;

	}

	public UFDate getDvoucherdate() {
		return dvoucherdate;
	}

	public void setDvoucherdate(UFDate dvoucherdate) {
		this.dvoucherdate = dvoucherdate;
	}

	public String getVvoucherid() {
		return vvoucherid;
	}

	public void setVvoucherid(String vvoucherid) {
		this.vvoucherid = vvoucherid;
	}

	public UFBoolean getVoucher() {
		return voucher;
	}

	public void setVoucher(UFBoolean voucher) {
		this.voucher = voucher;
	}

	public UFBoolean getUnittally() {
		return unittally;
	}

	public void setUnittally(UFBoolean unittally) {
		this.unittally = unittally;
	}

	public String getUnitplanitem() {
		return unitplanitem;
	}

	public void setUnitplanitem(String unitplanitem) {
		this.unitplanitem = unitplanitem;
	}

	public String getUnititem() {
		return unititem;
	}

	public void setUnititem(String unititem) {
		this.unititem = unititem;
	}

	public UFBoolean getWritePlan() {
		return writePlan;
	}

	public void setWritePlan(UFBoolean writePlan) {
		this.writePlan = writePlan;
	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2007-8-30
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_return";

	}
}