/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fbm.illegal;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2007-9-13
 * 
 * @author author
 * @version Your Project 1.0
 */
public class IllegalVO extends SuperVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// 非法票据主键
	public String pk_illegal;
	// 非法票据编号
	public String fbmbillno;
	// 币种
	public String pk_curr;
	// 票面金额
	public UFDouble moneyy;
	// 出票日期
	public UFDate invoicedate;
	// 截止日期
	public UFDate enddate;
	// 出票单位名称
	public String invoiceunitname;
	// 付款单位名称
	public String payunitname;
	// 收款单位名称
	public String receiveunitname;
	public UFDateTime ts;
	public Integer dr;
	public String note;

	public static final String NOTE = "note";
	public static final String PK_ILLEGAL = "pk_illegal";
	public static final String FBMBILLNO = "fbmbillno";
	public static final String PK_CURR = "pk_curr";
	public static final String MONEYY = "moneyy";
	public static final String INVOICEDATE = "invoicedate";
	public static final String ENDDATE = "enddate";
	public static final String INVOICEUNITNAME = "invoiceunitname";
	public static final String PAYUNITNAME = "payunitname";
	public static final String RECEIVEUNITNAME = "receiveunitname";
	public static final String DR = "dr";
	public static final String TS = "ts";

	public String getFbmbillno() {
		return fbmbillno;
	}

	public void setFbmbillno(String fbmbillno) {
		this.fbmbillno = fbmbillno;
	}

	public String getPk_curr() {
		return pk_curr;
	}

	public void setPk_curr(String pk_curr) {
		this.pk_curr = pk_curr;
	}

	public UFDouble getMoneyy() {
		return moneyy;
	}

	public void setMoneyy(UFDouble moneyy) {
		this.moneyy = moneyy;
	}

	public UFDate getInvoicedate() {
		return invoicedate;
	}

	public void setInvoicedate(UFDate invoicedate) {
		this.invoicedate = invoicedate;
	}

	public UFDate getEnddate() {
		return enddate;
	}

	public void setEnddate(UFDate enddate) {
		this.enddate = enddate;
	}

	public String getInvoiceunitname() {
		return invoiceunitname;
	}

	public void setInvoiceunitname(String invoiceunitname) {
		this.invoiceunitname = invoiceunitname;
	}

	public String getPayunitname() {
		return payunitname;
	}

	public void setPayunitname(String payunitname) {
		this.payunitname = payunitname;
	}

	public String getReceiveunitname() {
		return receiveunitname;
	}

	public void setReceiveunitname(String receiveunitname) {
		this.receiveunitname = receiveunitname;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2007-9-13
	 * 
	 * @return String
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2007-9-13
	 * 
	 * @param newTs
	 *            String
	 */
	public void setTs(UFDateTime newTs) {

		ts = newTs;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2007-9-13
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2007-9-13
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	public void setAttributeValue(String attributeName, Object value) {
		
		if (attributeName.equals(MONEYY)) {
			if (value != null)
				setMoneyy(new UFDouble(value.toString()));
		} else {
			super.setAttributeValue(attributeName, value);
		}	
		
	}
		
		
		/**
			 * 属性pk_illegal的Getter方法.
			 * 
			 * 创建日期:2007-9-13
			 * 
			 * @return String
			 */
	public String getPk_illegal() {
		return pk_illegal;
	}

	/**
	 * 属性pk_illegal的Setter方法.
	 * 
	 * 创建日期:2007-9-13
	 * 
	 * @param newPk_illegal
	 *            String
	 */
	public void setPk_illegal(String newPk_illegal) {

		pk_illegal = newPk_illegal;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2007-9-13
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID(
				"36200835", "UPP36200835-000004")/* @res"下列字段不能为空:" */);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-9-13
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-9-13
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return PK_ILLEGAL;
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-9-13
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_illegal";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2007-9-13
	 */
	public IllegalVO() {

		super();
	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2007-9-13
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_illegal";

	}

	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}

	/**
	 * @param note
	 *            the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}
}