/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fbm.reckon;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b> 调剂清算单主表VO
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2007-10-19
 * 
 * @author author bsrl
 * @version Your Project 5.02
 */
public class ReckonVO extends SuperVO {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	public String def5; // 自定义项5
	public String pk_corp;// 公司
	public String reckoncenter;// 清算票据中心
	public String reckonunit;// 清算单位
	public String voperatorid;// 操作员
	public String vapprovenote;// 审核批语
	public UFDouble brate;// 本币汇率
	public Integer vbillstatus;// 单据状态
	public String pk_org;// 组织
	public UFDouble frate;// 辅币汇率
	public UFDouble moneyf;// 辅币清算金额
	public String reckonaccname;// 清算单位账户名称（开户银行名称）
	public String vbillno;// 系统自动生成单据编号
	public String def1;// 自定义项1
	public String note;// 备注
	public String pk_billtypecode;// 单据类型
	public UFDate dapprovedate;// 审核日期
	public UFDate dreckondate;// 清算日期
	public String vapproveid;// 审核人
	public String def2;// 自定义项2
	public String def4;// 自定义项4
	public UFDouble moneyb;// 本币清算金额
	public String reckonno;// 清算单编号
	public String pk_curr;// 币种
	public String pk_reckon;// 主键
	public String def3;// 自定义项3
	public UFDate doperatedate;// 操作日期
	public UFDouble reckonmoneysum;// 清算金额汇总

	public UFDateTime ts;
	public Integer dr;

	public String vouchermanid;// 中心制证人
	public UFDate voucherdate;// 中心制证日期
	public String unitvouchermanid;// 单位制证人
	public UFDate unitvoucherdate;// 单位制证日期
	public String inacc;// 转入帐户
	public String outacc;// 转出帐户
	public UFBoolean unitvoucher;
	public UFBoolean centervoucher;
	public UFBoolean unittally;
	public UFDate dealdate;
	public String tallyman;// 记账人
	public UFDate tallydate;// 记账日期
	public String businessno;// 业务流水号

	private UFBoolean writebankacc;

	private UFBoolean writeinneracc;

	public UFBoolean getWritebankacc() {
		return writebankacc;
	}

	public void setWritebankacc(UFBoolean writebankacc) {
		this.writebankacc = writebankacc;
	}

	public UFBoolean getWriteinneracc() {
		return writeinneracc;
	}

	public void setWriteinneracc(UFBoolean writeinneracc) {
		this.writeinneracc = writeinneracc;
	}

	public static final String VOUCHERMANID = "vouchermanid";// 中心制证人
	public static final String VOUCHERDATE = "voucherdate";// 中心制证日期
	public static final String UNITVOUCHERMANID = "unitvouchermanid";// 单位制证人
	public static final String UNITVOUCHERDATE = "unitvoucherdate";// 单位制证日期

	public static final String DEF5 = "def5";
	public static final String PK_CORP = "pk_corp";
	public static final String RECKONCENTER = "reckoncenter";
	public static final String RECKONUNIT = "reckonunit";
	public static final String VOPERATORID = "voperatorid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String BRATE = "brate";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String PK_ORG = "pk_org";
	public static final String FRATE = "frate";
	public static final String MONEYF = "moneyf";
	public static final String RECKONACCNAME = "reckonaccname";
	public static final String VBILLNO = "vbillno";
	public static final String DEF1 = "def1";
	public static final String NOTE = "note";
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String DRECKONDATE = "dreckondate";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DEF2 = "def2";
	public static final String DEF4 = "def4";
	public static final String MONEYB = "moneyb";
	public static final String RECKONNO = "reckonno";
	public static final String PK_CURR = "pk_curr";
	public static final String PK_RECKON = "pk_reckon";
	public static final String DEF3 = "def3";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String RECKONMONEYSUM = "reckonmoneysum";
	public static final String INACC = "inacc";
	public static final String OUTACC = "outacc";
	public static final String UNITTALLY = "unittally";
	public static final String UNITVOUCHER = "unitvoucher";
	public static final String CENTERVOUCHER = "centervoucher";
	public static final String DEALDATE = "dealdate";
	public static final String TALLYMAN = "tallyman";
	public static final String TALLYDATE = "tallydate";

	public static final String TS = "ts";
	public static final String DR = "dr";

	/**
	 * @return the ts
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * @param ts
	 *            the ts to set
	 */
	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	/**
	 * @return the dr
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * @param dr
	 *            the dr to set
	 */
	public void setDr(Integer dr) {
		this.dr = dr;
	}

	/**
	 * @return the vouchermanid
	 */
	public String getVouchermanid() {
		return vouchermanid;
	}

	/**
	 * @param vouchermanid
	 *            the vouchermanid to set
	 */
	public void setVouchermanid(String vouchermanid) {
		this.vouchermanid = vouchermanid;
	}

	/**
	 * @return the voucherdate
	 */
	public UFDate getVoucherdate() {
		return voucherdate;
	}

	/**
	 * @param voucherdate
	 *            the voucherdate to set
	 */
	public void setVoucherdate(UFDate voucherdate) {
		this.voucherdate = voucherdate;
	}

	/**
	 * @return the unitvouchermanid
	 */
	public String getUnitvouchermanid() {
		return unitvouchermanid;
	}

	/**
	 * @param unitvouchermanid
	 *            the unitvouchermanid to set
	 */
	public void setUnitvouchermanid(String unitvouchermanid) {
		this.unitvouchermanid = unitvouchermanid;
	}

	/**
	 * @return the unitvoucherdate
	 */
	public UFDate getUnitvoucherdate() {
		return unitvoucherdate;
	}

	/**
	 * @param unitvoucherdate
	 *            the unitvoucherdate to set
	 */
	public void setUnitvoucherdate(UFDate unitvoucherdate) {
		this.unitvoucherdate = unitvoucherdate;
	}

	/**
	 * 属性def5的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDef5
	 *            String
	 */
	public void setDef5(String newDef5) {

		def5 = newDef5;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性reckoncenter的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getReckoncenter() {
		return reckoncenter;
	}

	/**
	 * 属性reckoncenter的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newReckoncenter
	 *            String
	 */
	public void setReckoncenter(String newReckoncenter) {

		reckoncenter = newReckoncenter;
	}

	/**
	 * 属性reckonunit的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getReckonunit() {
		return reckonunit;
	}

	/**
	 * 属性reckonunit的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newReckonunit
	 *            String
	 */
	public void setReckonunit(String newReckonunit) {

		reckonunit = newReckonunit;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性brate的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDouble
	 */
	public UFDouble getBrate() {
		return brate;
	}

	/**
	 * 属性brate的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newBrate
	 *            UFDouble
	 */
	public void setBrate(UFDouble newBrate) {

		brate = newBrate;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性pk_org的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newPk_org
	 *            String
	 */
	public void setPk_org(String newPk_org) {

		pk_org = newPk_org;
	}

	/**
	 * 属性frate的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDouble
	 */
	public UFDouble getFrate() {
		return frate;
	}

	/**
	 * 属性frate的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newFrate
	 *            UFDouble
	 */
	public void setFrate(UFDouble newFrate) {

		frate = newFrate;
	}

	/**
	 * 属性moneyf的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyf() {
		return moneyf;
	}

	/**
	 * 属性moneyf的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newMoneyf
	 *            UFDouble
	 */
	public void setMoneyf(UFDouble newMoneyf) {

		moneyf = newMoneyf;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性def1的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDef1
	 *            String
	 */
	public void setDef1(String newDef1) {

		def1 = newDef1;
	}

	/**
	 * 属性note的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/**
	 * 属性note的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newNote
	 *            String
	 */
	public void setNote(String newNote) {

		note = newNote;
	}

	/**
	 * 属性pk_billtypecode的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getPk_billtypecode() {
		return pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newPk_billtypecode
	 *            String
	 */
	public void setPk_billtypecode(String newPk_billtypecode) {

		pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {

		dapprovedate = newDapprovedate;
	}

	/**
	 * 属性dreckondate的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDate
	 */
	public UFDate getDreckondate() {
		return dreckondate;
	}

	/**
	 * 属性dreckondate的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDreckondate
	 *            UFDate
	 */
	public void setDreckondate(UFDate newDreckondate) {

		dreckondate = newDreckondate;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {

		vapproveid = newVapproveid;
	}

	/**
	 * 属性def2的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDef2
	 *            String
	 */
	public void setDef2(String newDef2) {

		def2 = newDef2;
	}

	/**
	 * 属性def4的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDef4
	 *            String
	 */
	public void setDef4(String newDef4) {

		def4 = newDef4;
	}

	/**
	 * 属性moneyb的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDouble
	 */
	public UFDouble getMoneyb() {
		return moneyb;
	}

	/**
	 * 属性moneyb的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newMoneyb
	 *            UFDouble
	 */
	public void setMoneyb(UFDouble newMoneyb) {

		moneyb = newMoneyb;
	}

	/**
	 * 属性reckonno的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getReckonno() {
		return reckonno;
	}

	/**
	 * 属性reckonno的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newReckonno
	 *            String
	 */
	public void setReckonno(String newReckonno) {

		reckonno = newReckonno;
	}

	/**
	 * 属性pk_curr的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getPk_curr() {
		return pk_curr;
	}

	/**
	 * 属性pk_curr的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newPk_curr
	 *            String
	 */
	public void setPk_curr(String newPk_curr) {

		pk_curr = newPk_curr;
	}

	/**
	 * 属性pk _reckon的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getPk_reckon() {
		return pk_reckon;
	}

	/**
	 * 属性pk _reckon的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newPk
	 *            _reckon String
	 */
	public void setPk_reckon(String newPk_reckon) {

		pk_reckon = newPk_reckon;
	}

	/**
	 * 属性def3的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDef3
	 *            String
	 */
	public void setDef3(String newDef3) {

		def3 = newDef3;
	}

	/**
	 * 属性doperatedate的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDate
	 */
	public UFDate getDoperatedate() {
		return doperatedate;
	}

	/**
	 * 属性doperatedate的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newDoperatedate
	 *            UFDate
	 */
	public void setDoperatedate(UFDate newDoperatedate) {

		doperatedate = newDoperatedate;
	}

	/**
	 * 属性reckonmoneysum的Getter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReckonmoneysum() {
		return reckonmoneysum;
	}

	/**
	 * 属性reckonmoneysum的Setter方法.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newReckonmoneysum
	 *            UFDouble
	 */
	public void setReckonmoneysum(UFDouble newReckonmoneysum) {

		reckonmoneysum = newReckonmoneysum;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_reckon == null) {
			errFields.add(new String("pk_reckon"));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("36201050", "UPP36201050-000002")/*
																											 * @res
																											 * "下列字段不能为空:"
																											 */);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-10-19
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-10-19
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_reckon";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-10-19
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "fbm_reckon";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2007-10-19
	 */
	public ReckonVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newPk
	 *            _reckon 主键值
	 */
	public ReckonVO(String newPk_reckon) {

		// 为主键字段赋值:
		pk_reckon = newPk_reckon;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_reckon;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @param newPk
	 *            _reckon String
	 */
	public void setPrimaryKey(String newPk_reckon) {

		pk_reckon = newPk_reckon;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2007-10-19
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "fbm_reckon";

	}

	public String getReckonaccname() {
		return reckonaccname;
	}

	public void setReckonaccname(String reckonaccname) {
		this.reckonaccname = reckonaccname;
	}

	public String getInacc() {
		return inacc;
	}

	public void setInacc(String inacc) {
		this.inacc = inacc;
	}

	public String getOutacc() {
		return outacc;
	}

	public void setOutacc(String outacc) {
		this.outacc = outacc;
	}

	public UFBoolean getUnitvoucher() {
		return unitvoucher;
	}

	public void setUnitvoucher(UFBoolean unitvoucher) {
		this.unitvoucher = unitvoucher;
	}

	public UFBoolean getCentervoucher() {
		return centervoucher;
	}

	public void setCentervoucher(UFBoolean centervoucher) {
		this.centervoucher = centervoucher;
	}

	public UFBoolean getUnittally() {
		return unittally;
	}

	public void setUnittally(UFBoolean unittally) {
		this.unittally = unittally;
	}

	public UFDate getDealdate() {
		return dealdate;
	}

	public void setDealdate(UFDate dealdate) {
		this.dealdate = dealdate;
	}

	public String getTallyman() {
		return tallyman;
	}

	public void setTallyman(String tallyman) {
		this.tallyman = tallyman;
	}

	public UFDate getTallydate() {
		return tallydate;
	}

	public void setTallydate(UFDate tallydate) {
		this.tallydate = tallydate;
	}

	public String getBusinessno() {
		return businessno;
	}

	public void setBusinessno(String businessno) {
		this.businessno = businessno;
	}
}